"""Independent verification: re-solve every puzzle without using stored keys."""
from __future__ import annotations
import json, os, sys, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cipher import word_tokens, encrypt
from solver import load_dictionary, count_solutions, letters_match

BANDS = ["Easy", "Medium", "Hard", "Expert"]


def main():
    t0 = time.time()
    root = os.path.join(os.path.dirname(__file__), "..")
    data = json.load(open(os.path.join(root, "data.json")))
    all_words = set()
    puzzles = []
    for b in ["Example"] + BANDS:
        for p in data[b]:
            puzzles.append(p)
            all_words.update(word_tokens(p["plaintext"]))
    dictionary = load_dictionary(extra_words=all_words)

    lines = []
    lines.append("# Verification report\n")
    lines.append("Generated by `src/verify.py` (independent of the stored substitution keys).\n")
    lines.append("")
    lines.append("Method:")
    lines.append("- Each puzzle is a monoalphabetic substitution cryptogram (bijective A–Z mapping).")
    lines.append("- An independent dictionary + domain-propagation / backtracking solver recovers English plaintexts consistent with the ciphertext pattern and any printed starter letters.")
    lines.append("- The solver never reads or applies the stored `key` field; it only uses `cipher`, `givens`, and the word dictionary.")
    lines.append("- A puzzle passes only if the solver finds **exactly one** plaintext and it matches the intended quote (alphabetic content).")
    lines.append("")

    rows = []
    failed = 0
    for p in puzzles:
        # Sanity: stored key encrypts plaintext to cipher (generator check, not uniqueness)
        key = p["key"]
        enc = "".join((key[ch.upper()] if ch.isalpha() else ch) for ch in p["plaintext"])
        key_ok = enc == p["cipher"]

        nsol, sols, status = count_solutions(
            p["cipher"], dictionary=dictionary, givens=p.get("givens") or {},
            limit=2, extra_words=all_words, node_limit=80_000,
        )
        unique_ok = status == "unique" and nsol == 1 and letters_match(sols[0], p["plaintext"])
        if not unique_ok or not key_ok:
            failed += 1
            check = f"FAIL status={status} n={nsol} key_ok={key_ok}"
        else:
            check = "OK"
        label = "Ex" if p["band"] == "Example" else str(p["num"])
        rows.append((label, p["band"], p["n_givens"], p["n_letters"], p["n_distinct"],
                     p["author"], status, check, p["plaintext"][:48]))

    elapsed = time.time() - t0
    total = len(puzzles)
    passed = total - failed
    lines.append(f"Runtime: **{elapsed:.1f}s**.\n")
    lines.append(f"- Puzzles checked: **{passed}/{total}** (including 1 worked example).")
    lines.append(f"- All passed with **exactly one** dictionary-consistent solution: **{'YES' if failed == 0 else 'NO'}**.")
    lines.append("")
    lines.append("| # | Band | Givens | Letters | Distinct | Author | Solver | Check | Quote (start) |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} | {r[6]} | {r[7]} | {r[8]} |")
    lines.append("")

    # Band summary
    lines.append("## Band summary\n")
    for b in BANDS:
        ps = data[b]
        gs = [p["n_givens"] for p in ps]
        lines.append(f"- **{b}**: {len(ps)} puzzles, starter letters avg {sum(gs)/len(gs):.2f} "
                     f"(min {min(gs)}, max {max(gs)})")
    lines.append("")

    out = os.path.join(root, "verification.md")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"verification.md: {passed}/{total} passed in {elapsed:.1f}s", flush=True)
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
