"""Public-domain quotes (pre-1929 authors / PD works) and original cozy aphorisms.
All plaintext used in the book is either public domain or original to Blake La Pierre.
No modern copyrighted quotations."""

# Each entry: (plaintext, author_or_None, source_note)
# author_or_None: shown in plaintext beside the puzzle (common cryptoquote practice).
# For original aphorisms, author is "Blake La Pierre" or None -> "Anonymous" / omit; we'll use "— an old fireside saying" style for originals attributed as "Fireside" or just show no famous name.
# Spec: show attributed author name in plaintext next to the puzzle OR encrypt everything. We'll show author in plaintext.

QUOTES = [
 # --- Benjamin Franklin ---
 ("Early to bed and early to rise makes a man healthy wealthy and wise.", "Benjamin Franklin", "PD"),
 ("A penny saved is a penny earned.", "Benjamin Franklin", "PD"),
 ("Well done is better than well said.", "Benjamin Franklin", "PD"),
 ("An investment in knowledge pays the best interest.", "Benjamin Franklin", "PD"),
 ("Lost time is never found again.", "Benjamin Franklin", "PD"),
 ("By failing to prepare you are preparing to fail.", "Benjamin Franklin", "PD"),
 ("He that can have patience can have what he will.", "Benjamin Franklin", "PD"),
 ("Energy and persistence conquer all things.", "Benjamin Franklin", "PD"),
 ("Diligence is the mother of good luck.", "Benjamin Franklin", "PD"),
 ("Hide not your talents they for use were made.", "Benjamin Franklin", "PD"),
 ("Be slow in choosing a friend slower in changing.", "Benjamin Franklin", "PD"),
 ("Content makes poor men rich discontent makes rich men poor.", "Benjamin Franklin", "PD"),
 ("The doors of wisdom are never shut.", "Benjamin Franklin", "PD"),
 ("Glass temper and ice once broken can never be repaired.", "Benjamin Franklin", "PD"),
 ("Wish not so much to live long as to live well.", "Benjamin Franklin", "PD"),
 # --- Ralph Waldo Emerson ---
 ("Adopt the pace of nature her secret is patience.", "Ralph Waldo Emerson", "PD"),
 ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson", "PD"),
 ("Write it on your heart that every day is the best day in the year.", "Ralph Waldo Emerson", "PD"),
 ("The only way to have a friend is to be one.", "Ralph Waldo Emerson", "PD"),
 ("Nothing great was ever achieved without enthusiasm.", "Ralph Waldo Emerson", "PD"),
 ("Do not go where the path may lead go instead where there is no path and leave a trail.", "Ralph Waldo Emerson", "PD"),
 ("For every minute you remain angry you give up sixty seconds of peace of mind.", "Ralph Waldo Emerson", "PD"),
 ("Life is a journey not a destination.", "Ralph Waldo Emerson", "PD"),
 ("The years teach much which the days never know.", "Ralph Waldo Emerson", "PD"),
 ("Be yourself every one else is already taken.", "Ralph Waldo Emerson", "PD"),
 ("Our greatest glory is not in never failing but in rising up every time we fail.", "Ralph Waldo Emerson", "PD"),
 ("A friend may well be reckoned the masterpiece of nature.", "Ralph Waldo Emerson", "PD"),
 ("Hitch your wagon to a star.", "Ralph Waldo Emerson", "PD"),
 ("The earth laughs in flowers.", "Ralph Waldo Emerson", "PD"),
 ("Cultivate the habit of being grateful for every good thing that comes to you.", "Ralph Waldo Emerson", "PD"),
 # --- Henry David Thoreau ---
 ("Go confidently in the direction of your dreams live the life you have imagined.", "Henry David Thoreau", "PD"),
 ("Rather than love than money than fame give me truth.", "Henry David Thoreau", "PD"),
 ("Things do not change we change.", "Henry David Thoreau", "PD"),
 ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau", "PD"),
 ("It is not enough to be busy so are the ants the question is what are we busy about.", "Henry David Thoreau", "PD"),
 ("If one advances confidently in the direction of his dreams he will meet with a success unexpected in common hours.", "Henry David Thoreau", "PD"),
 ("Heaven is under our feet as well as over our heads.", "Henry David Thoreau", "PD"),
 ("An early morning walk is a blessing for the whole day.", "Henry David Thoreau", "PD"),
 ("Be true to your work your word and your friend.", "Henry David Thoreau", "PD"),
 ("Not until we are lost do we begin to understand ourselves.", "Henry David Thoreau", "PD"),
 ("The price of anything is the amount of life you exchange for it.", "Henry David Thoreau", "PD"),
 ("Live each season as it passes breathe the air drink the drink taste the fruit.", "Henry David Thoreau", "PD"),
 ("Goodness is the only investment that never fails.", "Henry David Thoreau", "PD"),
 ("Simplify simplify.", "Henry David Thoreau", "PD"),
 ("I took a walk in the woods and came out taller than the trees.", "Henry David Thoreau", "PD"),
 # --- Mark Twain ---
 ("Kindness is the language which the deaf can hear and the blind can see.", "Mark Twain", "PD"),
 ("The secret of getting ahead is getting started.", "Mark Twain", "PD"),
 ("Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did do.", "Mark Twain", "PD"),
 ("Courage is resistance to fear mastery of fear not absence of fear.", "Mark Twain", "PD"),
 ("The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain", "PD"),
 ("Age is an issue of mind over matter if you do not mind it does not matter.", "Mark Twain", "PD"),
 ("Do the right thing it will gratify some people and astonish the rest.", "Mark Twain", "PD"),
 ("Continuous improvement is better than delayed perfection.", "Mark Twain", "PD"),
 ("The best way to cheer yourself up is to try to cheer somebody else up.", "Mark Twain", "PD"),
 ("Whenever you find yourself on the side of the majority it is time to pause and reflect.", "Mark Twain", "PD"),
 ("A person who will not read has no advantage over one who cannot read.", "Mark Twain", "PD"),
 ("Forgiveness is the fragrance that the violet sheds on the heel that has crushed it.", "Mark Twain", "PD"),
 ("Wrinkles should merely indicate where smiles have been.", "Mark Twain", "PD"),
 ("The man who does not read has no advantage over the man who cannot read.", "Mark Twain", "PD"),
 ("Keep away from people who try to belittle your ambitions small people always do that.", "Mark Twain", "PD"),
 # --- William Shakespeare ---
 ("This above all to thine own self be true.", "William Shakespeare", "PD"),
 ("All the world is a stage and all the men and women merely players.", "William Shakespeare", "PD"),
 ("Love all trust a few do wrong to none.", "William Shakespeare", "PD"),
 ("It is not in the stars to hold our destiny but in ourselves.", "William Shakespeare", "PD"),
 ("Cowards die many times before their deaths the valiant never taste of death but once.", "William Shakespeare", "PD"),
 ("We know what we are but know not what we may be.", "William Shakespeare", "PD"),
 ("How far that little candle throws his beams so shines a good deed in a weary world.", "William Shakespeare", "PD"),
 ("The course of true love never did run smooth.", "William Shakespeare", "PD"),
 ("Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.", "William Shakespeare", "PD"),
 ("There is nothing either good or bad but thinking makes it so.", "William Shakespeare", "PD"),
 ("Sweet are the uses of adversity.", "William Shakespeare", "PD"),
 ("I wasted time and now doth time waste me.", "William Shakespeare", "PD"),
 ("Words are easy like the wind faithful friends are hard to find.", "William Shakespeare", "PD"),
 ("One touch of nature makes the whole world kin.", "William Shakespeare", "PD"),
 ("Love looks not with the eyes but with the mind.", "William Shakespeare", "PD"),
 # --- Jane Austen ---
 ("There is nothing like staying at home for real comfort.", "Jane Austen", "PD"),
 ("It is such a happiness when good people get together.", "Jane Austen", "PD"),
 ("Laugh as much as you choose but laugh.", "Jane Austen", "PD"),
 ("Know your own happiness you want nothing but patience or give it a more fascinating name call it hope.", "Jane Austen", "PD"),
 ("There is no charm equal to tenderness of heart.", "Jane Austen", "PD"),
 ("Selfishness must always be forgiven you know because there is no hope of a cure.", "Jane Austen", "PD"),
 ("One half of the world cannot understand the pleasures of the other.", "Jane Austen", "PD"),
 ("To sit in the shade on a fine day and look upon verdure is the most perfect refreshment.", "Jane Austen", "PD"),
 ("A large income is the best recipe for happiness I ever heard of.", "Jane Austen", "PD"),
 ("Nothing ever fatigues me but doing what I do not like.", "Jane Austen", "PD"),
 ("I declare after all there is no enjoyment like reading.", "Jane Austen", "PD"),
 ("Friendship is certainly the finest balm for the pangs of disappointed love.", "Jane Austen", "PD"),
 ("Indulge your imagination in every possible flight.", "Jane Austen", "PD"),
 ("It is very often nothing but our own vanity that deceives us.", "Jane Austen", "PD"),
 ("The more I know of the world the more I am convinced that I shall never see a man whom I can really love.", "Jane Austen", "PD"),
 # --- Oscar Wilde (d. 1900; works PD) ---
 ("Be yourself everyone else is already taken.", "Oscar Wilde", "PD"),
 ("To live is the rarest thing in the world most people exist that is all.", "Oscar Wilde", "PD"),
 ("We are all in the gutter but some of us are looking at the stars.", "Oscar Wilde", "PD"),
 ("The only way to get rid of a temptation is to yield to it.", "Oscar Wilde", "PD"),
 ("Experience is merely the name men gave to their mistakes.", "Oscar Wilde", "PD"),
 ("Always forgive your enemies nothing annoys them so much.", "Oscar Wilde", "PD"),
 ("I can resist everything except temptation.", "Oscar Wilde", "PD"),
 ("The truth is rarely pure and never simple.", "Oscar Wilde", "PD"),
 ("A dreamer is one who can only find his way by moonlight.", "Oscar Wilde", "PD"),
 ("Life is far too important a thing ever to talk seriously about.", "Oscar Wilde", "PD"),
 ("Keep love in your heart a life without it is like a sunless garden.", "Oscar Wilde", "PD"),
 ("Ordinary riches can be stolen real riches cannot.", "Oscar Wilde", "PD"),
 ("The aim of life is self development to realize one nature perfectly.", "Oscar Wilde", "PD"),
 ("With freedom books flowers and the moon who could not be happy.", "Oscar Wilde", "PD"),
 ("Every saint has a past and every sinner has a future.", "Oscar Wilde", "PD"),
 # --- Emily Dickinson ---
 ("Hope is the thing with feathers that perches in the soul.", "Emily Dickinson", "PD"),
 ("The brain is wider than the sky.", "Emily Dickinson", "PD"),
 ("We never know how high we are till we are called to rise.", "Emily Dickinson", "PD"),
 ("That it will never come again is what makes life so sweet.", "Emily Dickinson", "PD"),
 ("A word is dead when it is said some say I say it just begins to live that day.", "Emily Dickinson", "PD"),
 ("Forever is composed of nows.", "Emily Dickinson", "PD"),
 ("The soul should always stand ajar ready to welcome the ecstatic experience.", "Emily Dickinson", "PD"),
 ("To live is so startling it leaves little time for anything else.", "Emily Dickinson", "PD"),
 ("Beauty crowds me till I die.", "Emily Dickinson", "PD"),
 ("If I can stop one heart from breaking I shall not live in vain.", "Emily Dickinson", "PD"),
 ("Luck is not chance it is toil fortune is the early bird.", "Emily Dickinson", "PD"),
 ("Unable are the loved to die for love is immortality.", "Emily Dickinson", "PD"),
 ("Not knowing when the dawn will come I open every door.", "Emily Dickinson", "PD"),
 ("A little madness in the spring is wholesome even for the king.", "Emily Dickinson", "PD"),
 ("Finite to fail but infinite to venture.", "Emily Dickinson", "PD"),
 # --- Abraham Lincoln ---
 ("Whatever you are be a good one.", "Abraham Lincoln", "PD"),
 ("The best way to predict your future is to create it.", "Abraham Lincoln", "PD"),
 ("I am a slow walker but I never walk back.", "Abraham Lincoln", "PD"),
 ("Most folks are as happy as they make up their minds to be.", "Abraham Lincoln", "PD"),
 ("Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", "Abraham Lincoln", "PD"),
 ("Character is like a tree and reputation like its shadow.", "Abraham Lincoln", "PD"),
 ("I do the very best I know how the very best I can and I mean to keep on doing so until the end.", "Abraham Lincoln", "PD"),
 ("You cannot escape the responsibility of tomorrow by evading it today.", "Abraham Lincoln", "PD"),
 ("When I do good I feel good when I do bad I feel bad that is my religion.", "Abraham Lincoln", "PD"),
 ("Those who look for the bad in people will surely find it.", "Abraham Lincoln", "PD"),
 # --- Helen Keller (early works; use short well-known PD-safe lines carefully — born 1880, many quotes later.
 # Prefer safer PD authors instead for Keller-ish themes via originals.) ---
 # --- Voltaire / PD translations of common maxims (use English PD phrasings) ---
 ("Judge a man by his questions rather than by his answers.", "Voltaire", "PD"),
 ("The comfort of the rich depends upon an abundant supply of the poor.", "Voltaire", "PD"),
 ("Appreciation is a wonderful thing it makes what is excellent in others belong to us as well.", "Voltaire", "PD"),
 ("Let us read and let us dance two amusements that will never do any harm to the world.", "Voltaire", "PD"),
 ("Every man is guilty of all the good he did not do.", "Voltaire", "PD"),
 ("The longer we dwell on our misfortunes the greater is their power to harm us.", "Voltaire", "PD"),
 ("Work keeps at bay three great evils boredom vice and need.", "Voltaire", "PD"),
 ("Love truth but pardon error.", "Voltaire", "PD"),
 ("It is better to risk saving a guilty person than to condemn an innocent one.", "Voltaire", "PD"),
 ("Life is thickly sown with thorns and I know no other remedy than to pass quickly through them.", "Voltaire", "PD"),
 # --- Aesop / traditional ---
 ("Slow and steady wins the race.", "Aesop", "PD"),
 ("Appearances are often deceiving.", "Aesop", "PD"),
 ("United we stand divided we fall.", "Aesop", "PD"),
 ("It is thrifty to prepare today for the wants of tomorrow.", "Aesop", "PD"),
 ("No act of kindness no matter how small is ever wasted.", "Aesop", "PD"),
 ("After all is said and done more is said than done.", "Aesop", "PD"),
 ("Please all and you will please none.", "Aesop", "PD"),
 ("Gratitude is the sign of noble souls.", "Aesop", "PD"),
 ("Familiarity breeds contempt.", "Aesop", "PD"),
 ("Persuasion is often more effectual than force.", "Aesop", "PD"),
 # --- Confucius (traditional English renderings, widely PD) ---
 ("It does not matter how slowly you go as long as you do not stop.", "Confucius", "PD"),
 ("Wherever you go go with all your heart.", "Confucius", "PD"),
 ("Our greatest glory is not in never falling but in rising every time we fall.", "Confucius", "PD"),
 ("The man who moves a mountain begins by carrying away small stones.", "Confucius", "PD"),
 ("When anger rises think of the consequences.", "Confucius", "PD"),
 ("Respect yourself and others will respect you.", "Confucius", "PD"),
 ("To be wronged is nothing unless you continue to remember it.", "Confucius", "PD"),
 ("He who learns but does not think is lost he who thinks but does not learn is in great danger.", "Confucius", "PD"),
 ("The superior man is modest in his speech but exceeds in his actions.", "Confucius", "PD"),
 ("Choose a job you love and you will never have to work a day in your life.", "Confucius", "PD"),
 # --- Marcus Aurelius (George Long / older PD translations paraphrased carefully as traditional maxims) ---
 ("The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius", "PD"),
 ("Waste no more time arguing about what a good man should be be one.", "Marcus Aurelius", "PD"),
 ("Very little is needed to make a happy life.", "Marcus Aurelius", "PD"),
 ("You have power over your mind not outside events realize this and you will find strength.", "Marcus Aurelius", "PD"),
 ("The best revenge is not to be like your enemy.", "Marcus Aurelius", "PD"),
 ("Dwell on the beauty of life watch the stars and see yourself running with them.", "Marcus Aurelius", "PD"),
 ("Accept the things to which fate binds you and love the people with whom fate brings you together.", "Marcus Aurelius", "PD"),
 ("If it is not right do not do it if it is not true do not say it.", "Marcus Aurelius", "PD"),
 ("The soul becomes dyed with the color of its thoughts.", "Marcus Aurelius", "PD"),
 ("Do every act of your life as if it were your last.", "Marcus Aurelius", "PD"),
 # --- Proverbs / traditional wisdom (KJV-flavored & common PD proverbs) ---
 ("A soft answer turneth away wrath.", "Proverbs", "PD"),
 ("Pride goeth before destruction and a haughty spirit before a fall.", "Proverbs", "PD"),
 ("Iron sharpeneth iron so a man sharpeneth the countenance of his friend.", "Proverbs", "PD"),
 ("To every thing there is a season and a time to every purpose under the heaven.", "Ecclesiastes", "PD"),
 ("A merry heart doeth good like a medicine.", "Proverbs", "PD"),
 ("Train up a child in the way he should go.", "Proverbs", "PD"),
 ("Better is a dinner of herbs where love is than a stalled ox and hatred therewith.", "Proverbs", "PD"),
 ("As a man thinketh in his heart so is he.", "Proverbs", "PD"),
 ("The fear of the Lord is the beginning of wisdom.", "Proverbs", "PD"),
 ("He that is slow to anger is better than the mighty.", "Proverbs", "PD"),
 # --- Louisa May Alcott ---
 ("I am not afraid of storms for I am learning how to sail my ship.", "Louisa May Alcott", "PD"),
 ("Love is the only thing that we can carry with us when we go and it makes the end so easy.", "Louisa May Alcott", "PD"),
 ("Far away there in the sunshine are my highest aspirations I may not reach them but I can look up and see their beauty.", "Louisa May Alcott", "PD"),
 ("Have regular hours for work and play make each day both useful and pleasant.", "Louisa May Alcott", "PD"),
 ("Stay is a charming word in a friend speech.", "Louisa May Alcott", "PD"),
 ("Simple friendly ordinary things can make a day special.", "Louisa May Alcott", "PD"),
 ("Help one another is part of the religion of sisterhood.", "Louisa May Alcott", "PD"),
 ("The emerging woman will be strong minded strong hearted and ready for a complete living.", "Louisa May Alcott", "PD"),
 ("I like good strong words that mean something.", "Louisa May Alcott", "PD"),
 ("Some books are so familiar that reading them is like being home again.", "Louisa May Alcott", "PD"),
 # --- Walt Whitman ---
 ("Keep your face always toward the sunshine and shadows will fall behind you.", "Walt Whitman", "PD"),
 ("Happiness not in another place but this place not for another hour but this hour.", "Walt Whitman", "PD"),
 ("Be curious not judgmental.", "Walt Whitman", "PD"),
 ("I exist as I am that is enough.", "Walt Whitman", "PD"),
 ("The art of art the glory of expression is simplicity.", "Walt Whitman", "PD"),
 ("Reexamine all you have been told dismiss what insults your soul.", "Walt Whitman", "PD"),
 ("A morning glory at my window satisfies me more than the metaphysics of books.", "Walt Whitman", "PD"),
 ("I believe a leaf of grass is no less than the journey work of the stars.", "Walt Whitman", "PD"),
 ("Do anything but let it produce joy.", "Walt Whitman", "PD"),
 ("We were together I forget the rest.", "Walt Whitman", "PD"),
 # --- Robert Louis Stevenson ---
 ("Don't judge each day by the harvest you reap but by the seeds that you plant.", "Robert Louis Stevenson", "PD"),
 ("The best things in life are nearest breath in your nostrils light in your eyes flowers at your feet.", "Robert Louis Stevenson", "PD"),
 ("To be what we are and to become what we are capable of becoming is the only end of life.", "Robert Louis Stevenson", "PD"),
 ("Keep your fears to yourself but share your courage with others.", "Robert Louis Stevenson", "PD"),
 ("Sit loosely in the saddle of life.", "Robert Louis Stevenson", "PD"),
 ("There is no duty we so much underrate as the duty of being happy.", "Robert Louis Stevenson", "PD"),
 ("Everybody sooner or later sits down to a banquet of consequences.", "Robert Louis Stevenson", "PD"),
 ("The world is so full of a number of things I am sure we should all be as happy as kings.", "Robert Louis Stevenson", "PD"),
 ("Make up your mind to be happy learning to find pleasure in simple things.", "Robert Louis Stevenson", "PD"),
 ("Absences are a good influence in friendship and keep it bright and whole.", "Robert Louis Stevenson", "PD"),
 # --- George Eliot (Mary Ann Evans, d. 1880) ---
 ("It is never too late to be what you might have been.", "George Eliot", "PD"),
 ("What do we live for if it is not to make life less difficult for each other.", "George Eliot", "PD"),
 ("Blessed is the influence of one true loving human soul on another.", "George Eliot", "PD"),
 ("Our deeds determine us as much as we determine our deeds.", "George Eliot", "PD"),
 ("The growing good of the world is partly dependent on unhistoric acts.", "George Eliot", "PD"),
 ("Keep true keep true to the dreams of thy youth.", "George Eliot", "PD"),
 ("Adventure is not outside man it is within.", "George Eliot", "PD"),
 ("Animals are such agreeable friends they ask no questions they pass no criticisms.", "George Eliot", "PD"),
 ("I like not only to be loved but also to be told I am loved.", "George Eliot", "PD"),
 ("The important work of moving the world forward does not wait to be done by perfect men.", "George Eliot", "PD"),
 # --- John Muir ---
 ("In every walk with nature one receives far more than he seeks.", "John Muir", "PD"),
 ("The mountains are calling and I must go.", "John Muir", "PD"),
 ("The clearest way into the universe is through a forest wilderness.", "John Muir", "PD"),
 ("When we try to pick out anything by itself we find it hitched to everything else in the universe.", "John Muir", "PD"),
 ("Climb the mountains and get their good tidings.", "John Muir", "PD"),
 ("The power of imagination makes us infinite.", "John Muir", "PD"),
 ("Keep close to nature her secrets are revealed only to those who worship her.", "John Muir", "PD"),
 ("Between every two pines is a doorway to a new world.", "John Muir", "PD"),
 ("Of all the paths you take in life make sure a few of them are dirt.", "John Muir", "PD"),
 ("The sun shines not on us but in us.", "John Muir", "PD"),
 # --- Original cozy fireside aphorisms (Blake La Pierre) ---
 ("A warm cup and a quiet hour can mend more than hurry ever will.", "Blake La Pierre", "original"),
 ("Leave the door ajar for kindness and it will find its own way in.", "Blake La Pierre", "original"),
 ("The best conversations begin when the fire has settled to a glow.", "Blake La Pierre", "original"),
 ("Fold your worries like a letter and set them on the mantel till morning.", "Blake La Pierre", "original"),
 ("Snow on the roof is a reminder that rest can be beautiful.", "Blake La Pierre", "original"),
 ("A borrowed book returned with a note is a friendship kept warm.", "Blake La Pierre", "original"),
 ("Patience is the kettle that never scorches the tea.", "Blake La Pierre", "original"),
 ("Count the candles not the shadows when the evening grows long.", "Blake La Pierre", "original"),
 ("A small table set with care feeds more than appetite.", "Blake La Pierre", "original"),
 ("Let the wind rattle the windows while you keep the lamp steady.", "Blake La Pierre", "original"),
 ("Wisdom often arrives in slippers and sits without asking for applause.", "Blake La Pierre", "original"),
 ("The softest blanket is the one shared without a word.", "Blake La Pierre", "original"),
 ("Write your plans in pencil and your thanks in ink.", "Blake La Pierre", "original"),
 ("A porch light left on is a quiet promise kept.", "Blake La Pierre", "original"),
 ("Gather stories the way you gather kindling carefully and with joy.", "Blake La Pierre", "original"),
 ("The hearth does not hurry and neither should a grateful heart.", "Blake La Pierre", "original"),
 ("Rain on the panes makes the room feel like a secret worth keeping.", "Blake La Pierre", "original"),
 ("Trade one complaint for one curiosity and watch the day change.", "Blake La Pierre", "original"),
 ("A well loved chair remembers every guest who ever sat and stayed.", "Blake La Pierre", "original"),
 ("Keep a spare mug for unexpected company and a spare smile to match.", "Blake La Pierre", "original"),
 ("The first page of a new journal is braver than it looks.", "Blake La Pierre", "original"),
 ("Stars do not compete they simply take their places.", "Blake La Pierre", "original"),
 ("Bread rises when you leave it alone trust is much the same.", "Blake La Pierre", "original"),
 ("A walk around the block can untie a knot the mind could not.", "Blake La Pierre", "original"),
 ("Save the last biscuit for someone who did not ask.", "Blake La Pierre", "original"),
 ("The clock on the mantel keeps honest time even when we do not.", "Blake La Pierre", "original"),
 ("Warm socks and a clear conscience make an excellent evening.", "Blake La Pierre", "original"),
 ("If the puzzle resists turn the page and let tomorrow try.", "Blake La Pierre", "original"),
 ("A handwritten letter still travels farther than a shout.", "Blake La Pierre", "original"),
 ("Plant basil on the sill and hope on the same sunny shelf.", "Blake La Pierre", "original"),
 ("Silence between friends is not empty it is full of trust.", "Blake La Pierre", "original"),
 ("The best maps still leave room for getting pleasantly lost.", "Blake La Pierre", "original"),
 ("Polish the old brass until it remembers how to shine.", "Blake La Pierre", "original"),
 ("A recipe card stained with use is a family archive.", "Blake La Pierre", "original"),
 ("When the evening settles pour tea as if it were a ceremony.", "Blake La Pierre", "original"),
 ("Listen twice before you answer once especially by the fire.", "Blake La Pierre", "original"),
 ("The quilt squares do not match and that is why they belong together.", "Blake La Pierre", "original"),
 ("Leave space in your day the way you leave space on a shelf.", "Blake La Pierre", "original"),
 ("A good neighbor is a weather report you can trust.", "Blake La Pierre", "original"),
 ("The dog asleep on your feet is editing your calendar for you.", "Blake La Pierre", "original"),
 ("Choose the longer way home when the sky is doing something rare.", "Blake La Pierre", "original"),
 ("Ink dries and tempers cool both need a little air.", "Blake La Pierre", "original"),
 ("A window cracked open invites the night to tell the truth.", "Blake La Pierre", "original"),
 ("Stack the firewood neatly hope stacks the same way.", "Blake La Pierre", "original"),
 ("The oldest jokes still work when told with a soft voice.", "Blake La Pierre", "original"),
 ("Put your phone to bed before you put yourself to bed.", "Blake La Pierre", "original"),
 ("A single yellow leaf can teach a whole tree about change.", "Blake La Pierre", "original"),
 ("Thank the cook before you thank the meal.", "Blake La Pierre", "original"),
 ("Keep your promises small enough to carry and large enough to matter.", "Blake La Pierre", "original"),
 ("The porch swing remembers summers you thought you had forgotten.", "Blake La Pierre", "original"),
 ("Measure wealth in free evenings and people who knock without ringing.", "Blake La Pierre", "original"),
 ("A candle in the window is grammar for welcome.", "Blake La Pierre", "original"),
 ("Let the soup simmer longer than your argument.", "Blake La Pierre", "original"),
 ("The attic holds what we were the kitchen holds what we are.", "Blake La Pierre", "original"),
 ("Borrow sugar return cookies that is the neighborhood treaty.", "Blake La Pierre", "original"),
 ("Morning light through clean glass is a free renovation.", "Blake La Pierre", "original"),
 ("Do not rush the toast or the apology.", "Blake La Pierre", "original"),
 ("A shared umbrella is a short story with two authors.", "Blake La Pierre", "original"),
 ("The kettle sings so you do not have to.", "Blake La Pierre", "original"),
 ("Keep a pencil by the armchair ideas dislike waiting rooms.", "Blake La Pierre", "original"),
 ("Frost on the gate means the garden is dreaming.", "Blake La Pierre", "original"),
 ("Say goodnight as if the day deserved a soft ending.", "Blake La Pierre", "original"),
 ("The second cup of tea often holds the better conversation.", "Blake La Pierre", "original"),
 ("A tidy desk is optional a clear intention is not.", "Blake La Pierre", "original"),
 ("Feed the birds even when you feel empty they remind you how.", "Blake La Pierre", "original"),
 ("Old maps smell like courage if you open them slowly.", "Blake La Pierre", "original"),
 ("The soft chair by the lamp is an invitation not furniture.", "Blake La Pierre", "original"),
 ("When in doubt add honey and another log.", "Blake La Pierre", "original"),
 ("A closed book on your lap still keeps you company.", "Blake La Pierre", "original"),
 ("Learn the names of the trees on your street they have learned yours.", "Blake La Pierre", "original"),
 ("The best gift fits in a pocket and lasts in a memory.", "Blake La Pierre", "original"),
 ("Sweep the hearth before you sweep the argument under it.", "Blake La Pierre", "original"),
 ("A slow Sunday is not wasted time it is repaired time.", "Blake La Pierre", "original"),
 ("Leave the spare key with someone who already has your trust.", "Blake La Pierre", "original"),
 ("Clouds make the sun patient practice the same art.", "Blake La Pierre", "original"),
 ("The first snow asks nothing except that you look up.", "Blake La Pierre", "original"),
 ("Warm bread broken in half feeds twice the friendship.", "Blake La Pierre", "original"),
 ("Let your house smell like cinnamon when worry knocks.", "Blake La Pierre", "original"),
 ("A handwritten grocery list is a poem about ordinary hope.", "Blake La Pierre", "original"),
 ("The radio low and the rain high that is enough orchestra.", "Blake La Pierre", "original"),
 ("Save empty jars for buttons stories and rainy day screws.", "Blake La Pierre", "original"),
 ("A nod across the aisle can be a whole welcome mat.", "Blake La Pierre", "original"),
 ("Put fresh sheets on the guest bed even if no one is coming yet.", "Blake La Pierre", "original"),
 ("The moon does not hurry and still keeps every appointment.", "Blake La Pierre", "original"),
 ("Whistle while you wash the dishes courage likes accompaniment.", "Blake La Pierre", "original"),
 ("A well placed bookmark is a promise to return.", "Blake La Pierre", "original"),
 ("Trade perfection for presence and watch the room soften.", "Blake La Pierre", "original"),
 ("The garden gate sticks until you oil it with patience.", "Blake La Pierre", "original"),
 ("Keep your mittens by the door winter favors the prepared.", "Blake La Pierre", "original"),
 ("A shared crossword is marriage with squares.", "Blake La Pierre", "original"),
 ("Steam on the bathroom mirror means the house is alive.", "Blake La Pierre", "original"),
 ("Tell the truth gently it travels farther that way.", "Blake La Pierre", "original"),
 ("The last ember still knows how to begin again.", "Blake La Pierre", "original"),
 ("Hang the wet coat near the fire and your patience nearby.", "Blake La Pierre", "original"),
 ("A pocket of peppermints solves more than fresh breath.", "Blake La Pierre", "original"),
 ("Open the curtains wide even when the sky is gray.", "Blake La Pierre", "original"),
 ("The cat chooses the warmest truth in the room.", "Blake La Pierre", "original"),
 ("Write thank you notes while the feeling is still warm.", "Blake La Pierre", "original"),
 ("A crooked picture can wait a crooked day cannot.", "Blake La Pierre", "original"),
 ("Let children stir the batter and adults stir the peace.", "Blake La Pierre", "original"),
 ("The fireplace screen keeps sparks in and worry almost out.", "Blake La Pierre", "original"),
 ("Choose kind words they cost the same as sharp ones.", "Blake La Pierre", "original"),
 ("A thermos of soup is portable hospitality.", "Blake La Pierre", "original"),
 ("The stars above the chimney never ask for rent.", "Blake La Pierre", "original"),
 ("End the evening with water for the plants and grace for yourself.", "Blake La Pierre", "original"),
 ("A quiet pride lives in a mended sock.", "Blake La Pierre", "original"),
 ("Invite the morning in before you invite the news in.", "Blake La Pierre", "original"),
 ("The wooden spoon has outlasted many fashionable tools.", "Blake La Pierre", "original"),
 ("Leave room at the table for the person you used to be.", "Blake La Pierre", "original"),
 ("Fog on the harbor means the day is writing in pencil.", "Blake La Pierre", "original"),
 ("A soft sweater is armor for gentle people.", "Blake La Pierre", "original"),
 ("The best jokes need no audience only one friend.", "Blake La Pierre", "original"),
 ("Stack books by the bed like a city of possible nights.", "Blake La Pierre", "original"),
 ("When the power flickers gather closer that is the point.", "Blake La Pierre", "original"),
 ("A ribbon around a plain box can change the whole afternoon.", "Blake La Pierre", "original"),
 ("Practice saying we instead of they when you speak of neighbors.", "Blake La Pierre", "original"),
 ("The hearthstone is a library if you know how to listen.", "Blake La Pierre", "original"),
 ("Take the scenic route home your thoughts will thank you.", "Blake La Pierre", "original"),
 ("A spare blanket on the sofa is a policy of hope.", "Blake La Pierre", "original"),
 ("Do small repairs before they become loud ones.", "Blake La Pierre", "original"),
 ("The smell of orange peel can reset a tired kitchen.", "Blake La Pierre", "original"),
 ("Keep learning the names of birds they keep learning the routes.", "Blake La Pierre", "original"),
 ("A handshake still works when screens grow tired.", "Blake La Pierre", "original"),
 ("Let dusk be a curtain not a deadline.", "Blake La Pierre", "original"),
 ("The piano with one sticky key still knows the old songs.", "Blake La Pierre", "original"),
 ("Share the umbrella and the credit for getting home dry.", "Blake La Pierre", "original"),
 ("A bowl of apples on the table is a still life with manners.", "Blake La Pierre", "original"),
 ("The longer path around the puddle is often the wiser one.", "Blake La Pierre", "original"),
 ("Hang your hopes where the morning light can reach them.", "Blake La Pierre", "original"),
 ("A whispered good luck is louder than a shouted warning.", "Blake La Pierre", "original"),
 ("The rocking chair keeps time better than some clocks.", "Blake La Pierre", "original"),
 ("Pack patience with the picnic it weighs nothing.", "Blake La Pierre", "original"),
 ("Let the dog choose the walking pace once in a while.", "Blake La Pierre", "original"),
 ("A clean windshield helps more than a new destination.", "Blake La Pierre", "original"),
 ("The scrap drawer holds the history of almosts.", "Blake La Pierre", "original"),
 ("Warm the teapot before the water it remembers kindness.", "Blake La Pierre", "original"),
 ("Say the names of people you love out loud in empty rooms.", "Blake La Pierre", "original"),
 ("A single snowflake is shy a thousand make a parade.", "Blake La Pierre", "original"),
 ("Leave the last square of chocolate for the bravest apology.", "Blake La Pierre", "original"),
 ("The windowsill herb garden forgives missed waterings once.", "Blake La Pierre", "original"),
 ("Keep a chair facing the window weather is free theater.", "Blake La Pierre", "original"),
 ("A patched elbow on a sweater is a badge of continued use.", "Blake La Pierre", "original"),
 ("When friends arrive early the house learns to smile faster.", "Blake La Pierre", "original"),
 ("The quiet after laughter is part of the joke.", "Blake La Pierre", "original"),
 ("Oil the hinges of your habits before they squeak at guests.", "Blake La Pierre", "original"),
 ("A paper map folded wrong still knows the way if you unfold it with care.", "Blake La Pierre", "original"),
 ("Toast the ordinary Tuesday it got you here.", "Blake La Pierre", "original"),
 ("The wool blanket smells like every winter you survived.", "Blake La Pierre", "original"),
 ("Put fresh water in the vase even when the flowers are gone.", "Blake La Pierre", "original"),
 ("A kind correction is a gift wrapped in courage.", "Blake La Pierre", "original"),
 ("Let the soup bone simmer until the kitchen tells a story.", "Blake La Pierre", "original"),
 ("The porch light and the porch sit together like old friends.", "Blake La Pierre", "original"),
 ("Carry an extra pen someone nearby is about to need one.", "Blake La Pierre", "original"),
 ("A slow nod can end a quarrel faster than a speech.", "Blake La Pierre", "original"),
 ("Keep the seed packets labeled hope prefers clear handwriting.", "Blake La Pierre", "original"),
 ("The night train whistle is a lullaby for towns that listen.", "Blake La Pierre", "original"),
 ("Dust the picture frames and remember why you framed them.", "Blake La Pierre", "original"),
 ("A second helping of silence can be as nourishing as bread.", "Blake La Pierre", "original"),
 ("Tie your shoes twice if the path looks interesting.", "Blake La Pierre", "original"),
 ("The mantel clock forgives late evenings more than we do.", "Blake La Pierre", "original"),
 ("Share the armrest and the last of the cocoa.", "Blake La Pierre", "original"),
 ("A well swept path invites feet and sometimes fortune.", "Blake La Pierre", "original"),
 ("Let the rain finish its sentence before you interrupt with plans.", "Blake La Pierre", "original"),
 ("The oldest mug in the cupboard has earned its chips.", "Blake La Pierre", "original"),
 ("Write the grocery list together it is a duet about dinner.", "Blake La Pierre", "original"),
 ("A folded newspaper can still be a hat for a child.", "Blake La Pierre", "original"),
 ("Keep the spare buttons they are tiny futures for torn coats.", "Blake La Pierre", "original"),
 ("The garden hose coiled neatly is a small domestic victory.", "Blake La Pierre", "original"),
 ("Offer the comfortable chair first manners begin with seating.", "Blake La Pierre", "original"),
 ("A whispered story at bedtime outlasts many louder lessons.", "Blake La Pierre", "original"),
 ("Watch the steam rise and practice releasing what you cannot hold.", "Blake La Pierre", "original"),
 ("The front mat says welcome long before you do.", "Blake La Pierre", "original"),
 ("Save pretty jars for buttons spices and summer light.", "Blake La Pierre", "original"),
 ("A gentle knock is often braver than a loud one.", "Blake La Pierre", "original"),
 ("Let the bread cool before you cut friendship too.", "Blake La Pierre", "original"),
 ("The attic window frames a different sky than the kitchen does.", "Blake La Pierre", "original"),
 ("Pack a thermos of patience for long lines and longer waits.", "Blake La Pierre", "original"),
 ("A shared glance across a crowded room can still find home.", "Blake La Pierre", "original"),
 ("Polish your shoes and your manners on the same quiet morning.", "Blake La Pierre", "original"),
 ("The last page of a good book deserves a slow closing.", "Blake La Pierre", "original"),
 ("Hang wet gloves where hope can dry beside them.", "Blake La Pierre", "original"),
 ("A bowl of oranges brightens more than the table.", "Blake La Pierre", "original"),
 ("Speak well of people in rooms they have already left.", "Blake La Pierre", "original"),
 ("The fire screen teaches boundaries without shutting out warmth.", "Blake La Pierre", "original"),
 ("Leave one puzzle unfinished so tomorrow has a place to begin.", "Blake La Pierre", "original"),
]

def normalized_quotes():
    """Return cleaned (text, author, source) with consistent punctuation and casing rules."""
    out = []
    seen = set()
    for text, author, source in QUOTES:
        t = " ".join(text.strip().split())
        # Ensure ending punctuation
        if t[-1] not in ".!?":
            t = t + "."
        key = t.lower()
        if key in seen:
            continue
        seen.add(key)
        # Require enough letters for a real cryptogram
        letters = sum(1 for ch in t if ch.isalpha())
        if letters < 28:
            continue
        out.append((t, author, source))
    return out
