"""The 40 cozy village scenes behind the puzzles of Logic on Lantern Lane (plus the worked example).

Each scene has a key category (usually first names), four other categories (at least one with an
order, such as times, prices or counts), three titles and three short story openings. A puzzle
uses the key plus 2, 3 or 4 of the other categories, so the openings never name a category.

Phrase templates:
  np    noun phrase for "the entity holding this value"   e.g. "the baker who brought the {v}"
  pred  predicate, past tense. Write "brought/bring the {v}": past form / base form, so the
        negative can be made ("did not bring the {v}"). Predicates that start with was/is/has
        are negated automatically ("was not", "is not", "does not have").
Ordered categories also carry lt / gt ("arrived earlier than") and dlt / dgt with {d}
("arrived {d} before"). {who} is the scene's noun for one entity.
"""

PEOPLE = [
    "Agnes", "Bea", "Clara", "Dot", "Edith", "Fern", "Gwen", "Hazel", "Iris", "June", "Kit", "Lottie",
    "Mabel", "Nell", "Olive", "Peggy", "Rosa", "Sadie", "Tilly", "Vera", "Winnie", "Ada", "Bertie",
    "Cyril", "Dennis", "Ernest", "Frank", "Gus", "Harold", "Ivor", "Jasper", "Ken", "Leo", "Monty",
    "Ned", "Oscar", "Percy", "Ray", "Stan", "Ted", "Walter", "Alfie", "Barney", "Colin", "Douglas",
    "Felix", "George", "Hugh", "Arthur", "Elsie", "Maud", "Ruby", "Lionel", "Norman", "Wilf", "Doris",
    "Martha", "Hettie", "Rupert", "Quentin", "Ursula", "Ida", "Bridget", "Cecil", "Flora", "Gilbert",
]
CATS = ["Biscuit", "Pickles", "Mittens", "Tuppence", "Marmalade", "Pepper", "Smudge", "Bramble", "Toffee",
        "Willow", "Sooty", "Nutmeg", "Crumpet", "Dumpling"]
COTTAGES = ["Rose Cottage", "Ivy Cottage", "Bramble End", "Holly House", "Fern Cottage", "Wren Cottage",
            "Apple Tree", "Old Forge", "Mill House", "Lark Rise"]
STREETS = ["Mill Lane", "Church Row", "Orchard Way", "Brook Street", "Hill Road", "Lantern Lane", "Duck Lane"]


def N(name, pool, np, pred):
    return dict(name=name, pool=pool, np=np, pred=pred, ordered=False)


def O(name, kind, values, np, pred, lt, gt, dlt, dgt, vf="{v}", lf=None, vf1=None, du=None):
    return dict(name=name, kind=kind, values=values, np=np, pred=pred, lt=lt, gt=gt, dlt=dlt, dgt=dgt,
                vf=vf, lf=lf or vf, vf1=vf1, du=du, ordered=True)


def TIME(name, start, step, count, verb, past, base, lt_word="earlier", gt_word="later", before="before", after="after"):
    """A clock-time category. past='arrived at', base='arrive at' (the base form makes the negative)."""
    vals = [start + i * step for i in range(count)]
    core = past[:-3] if past.endswith(" at") else past
    pw, bw = past.split()[0], base.split()[0]
    return O(name, "time", vals, np="the {who} who " + past + " {v}", pred=pw + "/" + bw + past[len(pw):] + " {v}",
             lt=core + " " + lt_word + " than", gt=core + " " + gt_word + " than",
             dlt=core + " {d} " + before, dgt=core + " {d} " + after)


def MONEY(name, start, step, count, np, pred, lt, gt, dlt, dgt):
    vals = [round(start + i * step, 2) for i in range(count)]
    return O(name, "money", vals, np, pred, lt, gt, dlt, dgt)


def COUNT(name, start, step, count, unit, np, pred, lt, gt, dlt, dgt, label="{v}"):
    """unit = (singular, plural). {v} in templates becomes e.g. '12 rows'; {d} a difference like 'four rows'."""
    vals = [start + i * step for i in range(count)]
    return O(name, "num", vals, np, pred, lt, gt, dlt, dgt, vf="{v} " + unit[1], vf1="{v} " + unit[0], lf=label, du=unit)


def PLAIN(name, start, step, count, du, np, pred, lt, gt, dlt, dgt):
    """Numbers shown bare (ages); du is the unit used in differences."""
    vals = [start + i * step for i in range(count)]
    return O(name, "num", vals, np, pred, lt, gt, dlt, dgt, du=du)


def ORDINAL(name, count, np, pred, lt, gt, dlt, dgt, du=("place", "places")):
    return O(name, "ordinal", list(range(1, count + 1)), np, pred, lt, gt, dlt, dgt, du=du)


def DAYS(name, np, pred):
    return O(name, "day", list(range(6)), np, pred, lt="came earlier in the week than", gt="came later in the week than",
             dlt="came {d} before", dgt="came {d} after", du=("day", "days"))


def S(id, who, titles, intros, cats, key="Name", keypool=None, keytense="was"):
    assert len(titles) == 3 and len(intros) == 3 and len(cats) == 4, id
    assert any(c["ordered"] for c in cats), id
    return dict(id=id, who=who, titles=titles, intros=intros, cats=cats, key=key,
                keypool=keypool or PEOPLE, keytense=keytense)


SCENES = [
S("bakesale", "baker",
  ["The Winter Bake Sale", "Cakes in the Church Hall", "Sold Out by Noon"],
  ["The church hall smelled of butter and cinnamon by eight o'clock. {N} bakers set out their best for the winter bake sale.",
   "Rain on the windows, cake on the tables. {N} bakers kept the church hall busy all morning.",
   "By noon every crumb was gone, and the organiser wanted the records straight for next year. {N} bakers took part."],
  [N("Bake", ["lemon tart", "ginger loaf", "apple pie", "cherry scones", "fudge", "carrot cake", "shortbread", "flapjacks"],
     "the baker who brought the {v}", "brought/bring the {v}"),
   MONEY("Price", 2, 1, 7, "the baker who charged {v}", "charged/charge {v}", "charged less than", "charged more than",
         "charged {d} less than", "charged {d} more than"),
   N("Cloth", ["blue cloth", "red cloth", "green cloth", "plaid cloth", "lace cloth", "white cloth", "yellow cloth"],
     "the baker with the {v}", "used/use the {v}"),
   TIME("Arrived", 480, 15, 8, "arrived", "arrived at", "arrive at")]),

S("knitting", "knitter",
  ["The Thursday Knitting Circle", "Needles by the Fire", "Purl and Plain"],
  ["Every Thursday the library lends its back room to the knitting circle. Tonight {n} knitters pulled their chairs close.",
   "The fire crackled and the needles clicked. {N} friends compared their progress before the tea came round.",
   "Plain, purl, plain, purl. {N} knitters counted rows and swapped gossip on a snowy evening."],
  [N("Project", ["scarf", "mittens", "tea cosy", "bobble hat", "cardigan", "blanket", "socks"],
     "the knitter making the {v}", "was making the {v}"),
   N("Yarn", ["cranberry", "moss green", "oatmeal", "navy", "mustard", "plum", "heather"],
     "the knitter using {v} yarn", "used/use {v} yarn"),
   COUNT("Rows", 12, 4, 7, ("row", "rows"), "the knitter who finished {v}", "finished/finish {v}",
         "finished fewer rows than", "finished more rows than", "finished {dn} fewer rows than", "finished {dn} more rows than"),
   N("Seat", ["window seat", "rocking chair", "wing chair", "armchair", "basket chair", "corner chair"],
     "the knitter in the {v}", "sat/sit in the {v}")]),

S("tearoom", "customer",
  ["Afternoon Tea at the Copper Kettle", "Four O'Clock Teas", "A Pot for One"],
  ["The Copper Kettle tea room was warm and full. The owner remembers every order, and today she served {n} regulars.",
   "When the clock struck four, the tea room filled with steam and chatter. {N} customers ordered at once.",
   "Snow outside, scones inside. {N} customers lingered at the Copper Kettle until the lamps came on."],
  [N("Tea", ["Earl Grey", "Darjeeling", "peppermint", "chamomile", "Assam", "rooibos", "jasmine"],
     "the customer who ordered {v}", "ordered/order {v}"),
   N("Treat", ["sponge cake", "scone", "eclair", "teacake", "macaroon", "brownie", "crumpet"],
     "the customer who had the {v}", "had/have the {v}"),
   N("Table", ["window table", "corner table", "fireside table", "booth", "counter seat", "garden table"],
     "the customer at the {v}", "sat/sit at the {v}"),
   MONEY("Bill", 4, 1, 7, "the customer whose bill was {v}", "paid/pay {v}", "paid less than", "paid more than",
         "paid {d} less than", "paid {d} more than")]),

S("bookshop", "shopper",
  ["The Second-Hand Bookshop", "Dusty Shelves", "A Rainy Hour of Browsing"],
  ["Old Mr Pell's bookshop has more rooms than seems possible. On Saturday {n} shoppers went home with a book each.",
   "A bell over the door, a cat on the counter and books to the ceiling. {N} shoppers found a treasure today.",
   "When the rain came down, {n} shoppers ducked into the bookshop and lost track of time."],
  [N("Book", ["poetry", "travel", "cookery", "gardening", "history", "birdwatching", "astronomy"],
     "the shopper who bought the {v} book", "bought/buy the {v} book"),
   MONEY("Price", 1, 1, 7, "the shopper who spent {v}", "spent/spend {v}", "spent less than", "spent more than",
         "spent {d} less than", "spent {d} more than"),
   N("Room", ["front room", "attic", "back room", "stairway", "cellar", "map room"],
     "the shopper who browsed the {v}", "browsed/browse the {v}"),
   COUNT("Stayed", 10, 10, 7, ("minute", "minutes"), "the shopper who stayed {v}", "stayed/stay {v}",
         "stayed a shorter time than", "stayed longer than", "stayed {d} less than", "stayed {d} longer than", label="{v} min")]),

S("snowmen", "builder",
  ["The Snowman Contest", "Carrots and Coal", "Judging on the Green"],
  ["After the first big snow, the village held its snowman contest on the green. {N} builders worked until their fingers tingled.",
   "Scarves, hats and a great deal of snow. {N} builders lined their snowmen up for the judge.",
   "The judge walked slowly round the green with her clipboard. {N} snowmen waited, and so did their builders."],
  [N("Hat", ["top hat", "bobble hat", "flat cap", "bowler", "beret", "straw hat", "tea cosy"],
     "the builder who chose the {v}", "chose/choose the {v}"),
   N("Nose", ["carrot", "parsnip", "pine cone", "button", "radish", "cork"],
     "the builder who used a {v} for the nose", "used/use a {v} for the nose"),
   COUNT("Score", 5, 1, 6, ("point", "points"), "the builder who scored {v}", "scored/score {v}",
         "scored fewer points than", "scored more points than", "scored {dn} fewer points than", "scored {dn} more points than"),
   N("Spot", ["by the pond", "by the oak", "by the gate", "by the bench", "by the church", "by the well"],
     "the builder {v}", "built/build {v}")]),

S("choir", "singer",
  ["Choir Practice", "Warming Up the Voices", "The Solo Auditions"],
  ["The village choir meets in the chapel on Tuesday evenings. This week {n} singers each chose a solo to practise.",
   "Coats off, scarves on, voices warming. {N} singers arrived for practice one frosty night.",
   "The choirmaster wanted a solo from everyone before the spring concert. {N} singers stepped up."],
  [N("Voice", ["soprano", "alto", "tenor", "bass", "baritone", "mezzo"],
     "the singer who sang {v}", "sang/sing {v}"),
   N("Song", ["Greensleeves", "Danny Boy", "Scarborough Fair", "Shenandoah", "Loch Lomond", "Amazing Grace"],
     "the singer who chose {v}", "chose/choose {v}"),
   TIME("Arrived", 1120, 5, 8, "arrived", "arrived at", "arrive at"),
   N("Folder", ["red folder", "blue folder", "green folder", "black folder", "yellow folder", "purple folder"],
     "the singer with the {v}", "carried/carry the {v}")]),

S("library", "reader",
  ["Due Back at the Library", "The Returns Trolley", "Quiet, Please"],
  ["The librarian likes her returns trolley tidy. This week {n} readers brought books back.",
   "Thump, thump, thump went the date stamp. {N} readers returned a book this week.",
   "A whisper, a cough, a turning page. {N} readers visited the little library over one snowy week."],
  [N("Section", ["travel", "history", "poetry", "cookery", "nature", "art", "music"],
     "the reader who returned the {v} book", "returned/return the {v} book"),
   COUNT("Kept", 7, 7, 6, ("day", "days"), "the reader who kept the book for {v}", "kept/keep the book for {v}",
         "kept the book for less time than", "kept the book longer than", "kept the book {d} less than", "kept the book {d} longer than"),
   O("Day", "day", list(range(6)), "the reader who came in on {v}", "came/come in on {v}", "came in earlier in the week than", "came in later in the week than", "came in {d} before", "came in {d} after", du=("day", "days")),
   N("Bag", ["tote bag", "basket", "rucksack", "satchel", "paper bag", "string bag"],
     "the reader with the {v}", "carried/carry a {v}")]),

S("pies", "entrant",
  ["The Great Pie Judging", "A Slice for the Judge", "Lattice and Crumble"],
  ["The pie table at the harvest supper bowed under its load. The judge tasted {n} pies and placed them all.",
   "One fork, one judge and {n} hopeful pie makers waiting in the village hall.",
   "Golden crusts and bubbling fillings. {N} entrants hoped their pie would take the ribbon."],
  [N("Pie", ["apple", "pumpkin", "pecan", "rhubarb", "blackberry", "cherry", "pear"],
     "the entrant who baked the {v} pie", "baked/bake the {v} pie"),
   ORDINAL("Place", 6, "the entrant who placed {v}", "placed/place {v}", "placed higher than", "placed lower than",
           "finished {d} ahead of", "finished {d} behind"),
   N("Top", ["lattice top", "crumble top", "plain top", "star pattern", "leaf pattern", "braided edge"],
     "the entrant whose pie had a {v}", "made/make a {v}"),
   N("Dish", ["blue dish", "tin plate", "glass dish", "white dish", "copper pan", "clay dish"],
     "the entrant who used the {v}", "used/use the {v}")]),

S("sledging", "child",
  ["Sledging on Hob Hill", "Down the Long Slope", "Snow Day"],
  ["School was closed for snow, so the long slope behind the church filled with sledges. {N} children stayed out till dusk.",
   "Whoosh, bump, laugh, climb, repeat. {N} children spent the whole afternoon on the hill.",
   "A snow day is the best kind of day. {N} children raced down the long slope and trudged back up again."],
  [N("Sled", ["wooden sled", "red toboggan", "saucer", "inner tube", "tea tray", "blue sledge"],
     "the child on the {v}", "rode/ride the {v}"),
   COUNT("Runs", 3, 1, 8, ("run", "runs"), "the child who made {v}", "made/make {v}",
         "made fewer runs than", "made more runs than", "made {dn} fewer runs than", "made {dn} more runs than"),
   N("Scarf", ["red scarf", "yellow scarf", "green scarf", "striped scarf", "spotted scarf", "blue scarf"],
     "the child in the {v}", "wore/wear the {v}"),
   PLAIN("Age", 5, 1, 7, ("year", "years"), "the child aged {v}", "is {v} years old",
         "is younger than", "is older than", "is {d} younger than", "is {d} older than")]),

S("market", "stallholder",
  ["The Saturday Market", "Stalls in the Square", "Frost on the Canopies"],
  ["The winter market fills the square every Saturday, frost or no frost. {N} stallholders set up early.",
   "Steam from the urn, chatter from the queue. {N} stallholders did good business in the square.",
   "The canopies were white with frost when the first stallholders arrived. {N} of them traded all morning."],
  [N("Goods", ["honey", "cheese", "jam", "candles", "eggs", "bread", "apples"],
     "the stallholder selling {v}", "sold/sell {v}"),
   TIME("Set up", 390, 15, 8, "set up", "set up at", "set up at"),
   N("Canopy", ["green canopy", "white canopy", "striped canopy", "red canopy", "blue canopy", "yellow canopy"],
     "the stallholder under the {v}", "put/put up the {v}"),
   MONEY("Takings", 20, 10, 7, "the stallholder who took in {v}", "took/take in {v}", "took in less than",
         "took in more than", "took in {d} less than", "took in {d} more than")]),

S("lanterns", "walker",
  ["The Lantern Parade", "Lights Along the Lane", "A Procession of Paper Moons"],
  ["On the darkest night of the year the village walks Lantern Lane with home-made lanterns. {N} walkers led the parade.",
   "Paper, glue and a candle in a jar. {N} walkers carried their lanterns from the church to the green.",
   "The lane glowed gold as the parade went by. {N} walkers stayed in a tidy line the whole way."],
  [N("Lantern", ["star", "moon", "fish", "owl", "house", "heart", "boat"],
     "the walker with the {v} lantern", "carried/carry the {v} lantern"),
   ORDINAL("Position", 6, "the walker who was {v} in line", "was {v} in line", "walked ahead of", "walked behind",
           "walked {d} ahead of", "walked {d} behind"),
   N("Paper", ["red paper", "gold paper", "blue paper", "green paper", "white paper", "orange paper"],
     "the walker whose lantern used {v}", "used/use {v}"),
   N("Street", STREETS, "the walker from {v}", "came/come from {v}")]),

S("seeds", "gardener",
  ["The January Seed Swap", "Packets on the Trestle", "Planning for Spring"],
  ["Gardeners can't garden in January, so they swap seeds instead. {N} of them met in the village hall.",
   "Little paper packets, big plans for spring. {N} gardeners swapped seeds over tea and biscuits.",
   "Snow lay on the allotments while {n} gardeners talked about summer in the warm hall."],
  [N("Seeds", ["sweet peas", "runner beans", "sunflowers", "tomatoes", "marigolds", "poppies", "radishes"],
     "the gardener who swapped {v}", "swapped/swap {v}"),
   COUNT("Packets", 4, 1, 7, ("packet", "packets"), "the gardener who brought {v}", "brought/bring {v}",
         "brought fewer packets than", "brought more packets than", "brought {dn} fewer packets than", "brought {dn} more packets than"),
   N("Wellies", ["green", "yellow", "red", "navy", "floral", "spotty"],
     "the gardener in {v} wellies", "wore/wear {v} wellies"),
   COUNT("Years", 2, 2, 7, ("year", "years"), "the gardener with {v} of experience", "has gardened for {v}",
         "has gardened for fewer years than", "has gardened for more years than",
         "has gardened {dn} years less than", "has gardened {dn} years more than")]),

S("cats", "cat",
  ["Cats of Lantern Lane", "Who Naps Where?", "The Rescue Cats Find Homes"],
  ["Lantern Lane has more cats than chimneys. The vet keeps notes on {n} of them.",
   "Every cat on the lane has a favourite napping place and a person who thinks they're in charge. Here are {n}.",
   "The animal shelter found homes for {n} cats this winter, all on the same lane."],
  [N("Owner", PEOPLE[:30], "the cat who lives with {v}", "~lives/live with {v}"),
   COUNT("Age", 1, 1, 7, ("year", "years"), "the cat who is {v} old", "is {v} old",
         "is younger than", "is older than", "is {d} younger than", "is {d} older than"),
   N("Napping spot", ["windowsill", "armchair", "bookshelf", "hearth rug", "piano", "stairs", "radiator"],
     "the cat who naps on the {v}", "~naps/nap on the {v}"),
   COUNT("Weight", 7, 1, 7, ("lb", "lb"), "the cat who weighs {v}", "~weighs/weigh {v}",
         "weighs less than", "weighs more than", "weighs {d} less than", "weighs {d} more than")],
  key="Cat", keypool=CATS, keytense="is"),

S("dogs", "walker",
  ["Dog Walkers at Dawn", "Paw Prints in the Snow", "The Early Walk"],
  ["Before the village wakes, the dog walkers are out. {N} of them crossed paths on the common this morning.",
   "Fresh snow shows exactly who went where. {N} dog walkers left their tracks on the common.",
   "Frost, breath clouds and wagging tails. {N} walkers took their dogs out early."],
  [N("Breed", ["beagle", "collie", "spaniel", "terrier", "labrador", "dachshund", "poodle"],
     "the walker with the {v}", "walked/walk the {v}"),
   N("Dog", ["Rufus", "Daisy", "Bonnie", "Scout", "Pippin", "Hamish", "Juno"],
     "{v}'s owner", "~owns/own {v}"),
   TIME("Set out", 375, 15, 8, "set out", "set out at", "set out at"),
   COUNT("Distance", 1, 1, 7, ("mile", "miles"), "the walker who went {v}", "walked/walk {v}",
         "walked a shorter way than", "walked farther than", "walked {d} less than", "walked {d} farther than")]),

S("skating", "skater",
  ["Skating on Mill Pond", "Round and Round the Ice", "The Frozen Pond"],
  ["When Mill Pond froze solid, half the village came out with skates. {N} skaters stayed until the lamps were lit.",
   "Scrape, glide, wobble, glide. {N} skaters circled the pond on a bright cold afternoon.",
   "The pond keeper declared the ice safe at last. {N} skaters were the first ones on."],
  [COUNT("Laps", 4, 1, 7, ("lap", "laps"), "the skater who skated {v}", "skated/skate {v}",
         "skated fewer laps than", "skated more laps than", "skated {dn} fewer laps than", "skated {dn} more laps than"),
   N("Hat", ["bobble hat", "earmuffs", "beanie", "fur hat", "beret", "headband"],
     "the skater in the {v}", "wore/wear the {v}"),
   N("Drink", ["cocoa", "cider", "tea", "coffee", "chai", "lemon and honey"],
     "the skater who drank {v} afterwards", "drank/drink {v} afterwards"),
   TIME("Arrived", 840, 15, 8, "arrived", "arrived at", "arrive at")]),

S("quilting", "quilter",
  ["The Quilting Bee", "Patchwork Afternoon", "Stitch by Stitch"],
  ["The quilting bee meets around the big table at Holly House. This afternoon {n} quilters each worked on a block.",
   "Scraps, thread and a good long chat. {N} quilters spent a wet afternoon stitching together.",
   "Every square tells a story. {N} quilters added theirs to the village quilt."],
  [N("Block", ["log cabin", "star", "nine-patch", "pinwheel", "flying geese", "bear paw", "basket"],
     "the quilter sewing the {v} block", "sewed/sew the {v} block"),
   N("Fabric", ["indigo", "rose", "sage", "saffron", "rust", "cream", "lilac"],
     "the quilter who used {v} fabric", "used/use {v} fabric"),
   COUNT("Squares", 6, 1, 7, ("square", "squares"), "the quilter who finished {v}", "finished/finish {v}",
         "finished fewer squares than", "finished more squares than", "finished {dn} fewer squares than", "finished {dn} more squares than"),
   COUNT("Experience", 3, 3, 7, ("year", "years"), "the quilter with {v} of experience", "has quilted for {v}",
         "has quilted for fewer years than", "has quilted for more years than",
         "has quilted {dn} years less than", "has quilted {dn} years more than")]),

S("chess", "player",
  ["The Chess Club Ladder", "Check by the Fireside", "Knights at the Village Hall"],
  ["The chess club's winter ladder ran for six weeks. When it ended, {n} players compared their results.",
   "Clocks ticking, kettle boiling. {N} players met at the village hall for the last night of the ladder.",
   "No one says much at chess club, but everyone keeps score. {N} players finished the winter ladder."],
  [COUNT("Wins", 1, 1, 7, ("game", "games"), "the player who won {v}", "won/win {v}",
         "won fewer games than", "won more games than", "won {dn} fewer games than", "won {dn} more games than"),
   N("Piece", ["knight", "bishop", "rook", "queen", "pawn", "king"],
     "the player whose favourite piece is the {v}", "~favours/favour the {v}"),
   N("Snack", ["pretzels", "shortbread", "apples", "crisps", "toffee", "oatcakes", "walnuts"],
     "the player who brought {v}", "brought/bring {v}"),
   PLAIN("Age", 30, 10, 6, ("year", "years"), "the player aged {v}", "is {v} years old",
         "is younger than", "is older than", "is {d} younger than", "is {d} older than")]),

S("jigsaw", "puzzler",
  ["The Jigsaw Swap", "A Box of a Thousand Pieces", "Corners First"],
  ["Once a month the library hosts a jigsaw swap. {N} puzzlers each took a new box home and reported back.",
   "Edges first, then the sky, then the tricky bit in the middle. {N} puzzlers finished their swap puzzles this month.",
   "The swap table had stacks of boxes. {N} puzzlers each chose one and raced to finish it."],
  [N("Picture", ["lighthouse", "harbour", "cottage garden", "steam train", "market square", "owls", "teapots"],
     "the puzzler who took the {v} puzzle", "took/take the {v} puzzle"),
   COUNT("Pieces", 250, 250, 6, ("piece", "pieces"), "the puzzler whose puzzle had {v}", "picked/pick a puzzle with {v}",
         "picked a puzzle with fewer pieces than", "picked a puzzle with more pieces than",
         "picked a puzzle with {dn} fewer pieces than", "picked a puzzle with {dn} more pieces than"),
   COUNT("Days", 2, 1, 7, ("day", "days"), "the puzzler who took {v}", "took/take {v}",
         "finished in fewer days than", "took more days than", "finished {d} sooner than", "took {d} longer than"),
   N("Mug", ["spotted mug", "owl mug", "striped mug", "plain mug", "floral mug", "tin mug"],
     "the puzzler with the {v}", "drank/drink from the {v}")]),

S("soup", "cook",
  ["The Soup Supper", "Ladles at the Ready", "Bowls All Round"],
  ["The soup supper raises money for the church roof every January. {N} cooks each made a big pot.",
   "Steam rose from every pot on the long table. {N} cooks served the whole village.",
   "Bring a bowl, take a seat. {N} cooks kept the village warm on the coldest night of the year."],
  [N("Soup", ["tomato", "mushroom", "pea", "carrot", "lentil", "onion", "parsnip"],
     "the cook who made the {v} soup", "made/make the {v} soup"),
   N("Bread", ["rye bread", "sourdough", "soda bread", "oat rolls", "cornbread", "cheese scones"],
     "the cook who served {v}", "served/serve {v}"),
   COUNT("Bowls", 10, 2, 7, ("bowl", "bowls"), "the cook who ladled out {v}", "ladled/ladle out {v}",
         "ladled out fewer bowls than", "ladled out more bowls than", "ladled out {dn} fewer bowls than", "ladled out {dn} more bowls than"),
   N("Pot", ["copper pot", "black pot", "blue pot", "enamel pot", "big tureen", "slow cooker"],
     "the cook with the {v}", "cooked/cook in the {v}")]),

S("station", "traveller",
  ["The Little Station", "Platform One", "Waiting for the Train"],
  ["Lantern Lane Halt has one platform, one bench and one very chatty porter. This morning he helped {n} travellers.",
   "The porter knows where everyone is going. {N} travellers waited on the platform this morning.",
   "Steam, whistles and a quick goodbye. {N} travellers caught a train from the little station."],
  [N("Going to", ["Fernley", "Oakhurst", "Saltmarsh", "Bellwick", "Hollins", "Wrenfield"],
     "the traveller going to {v}", "was going to {v}"),
   TIME("Train", 545, 10, 8, "left", "left at", "leave at"),
   N("Luggage", ["suitcase", "hatbox", "rucksack", "carpetbag", "parcel", "picnic basket"],
     "the traveller with the {v}", "carried/carry a {v}"),
   MONEY("Fare", 6, 1, 7, "the traveller whose fare was {v}", "paid/pay {v}", "paid less than", "paid more than",
         "paid {d} less than", "paid {d} more than")]),

S("pottery", "potter",
  ["The Pottery Class", "Clay on the Wheel", "Fresh from the Kiln"],
  ["The pottery class meets in the old forge. After the last firing, {n} potters set out their finished pieces.",
   "Wet clay, spinning wheels and a lot of laughing. {N} potters made something for the spring sale.",
   "The kiln door opened and everyone leaned in. {N} pieces came out whole, one for each potter."],
  [N("Piece", ["bowl", "vase", "jug", "teapot", "mug", "plate", "candlestick"],
     "the potter who made the {v}", "made/make the {v}"),
   N("Glaze", ["celadon", "cobalt", "honey", "white", "speckled", "rust"],
     "the potter who chose the {v} glaze", "chose/choose the {v} glaze"),
   COUNT("Lessons", 2, 1, 7, ("lesson", "lessons"), "the potter who has had {v}", "has had {v}",
         "has had fewer lessons than", "has had more lessons than", "has had {dn} fewer lessons than", "has had {dn} more lessons than"),
   MONEY("Price", 8, 1, 7, "the potter who priced the piece at {v}", "priced/price the piece at {v}",
         "priced the piece lower than", "priced the piece higher than", "priced the piece {d} lower than", "priced the piece {d} higher than")]),

S("birds", "watcher",
  ["The Winter Bird Count", "Robins and Wrens", "Binoculars at Dawn"],
  ["Each winter the village counts its garden birds for one morning. {N} watchers took part this year.",
   "Notebook, flask and binoculars. {N} watchers spread out around the village to count birds.",
   "It was cold, quiet and full of birdsong. {N} watchers tallied every feathered visitor."],
  [N("First bird", ["robin", "wren", "blue tit", "blackbird", "goldfinch", "nuthatch", "jay"],
     "the watcher whose first bird was a {v}", "saw/see a {v} first"),
   COUNT("Count", 12, 3, 7, ("bird", "birds"), "the watcher who counted {v}", "counted/count {v}",
         "counted fewer birds than", "counted more birds than", "counted {dn} fewer birds than", "counted {dn} more birds than"),
   N("Spot", ["orchard", "churchyard", "riverbank", "common", "village pond", "allotments"],
     "the watcher at the {v}", "watched/watch from the {v}"),
   TIME("Began", 420, 15, 8, "began", "began at", "begin at")]),

S("cocoa", "maker",
  ["The Cocoa Contest", "Hot Chocolate on the Green", "Marshmallows Optional"],
  ["The cocoa contest is the warmest event of the winter fair. {N} makers set up their stands on the green.",
   "Everyone has a secret recipe. {N} cocoa makers let the village taste theirs.",
   "Cold hands, warm mugs. {N} makers sold cocoa from little stands around the green."],
  [N("Topping", ["marshmallows", "whipped cream", "cinnamon", "nutmeg", "chocolate curls", "peppermint", "orange zest"],
     "the maker who added {v}", "added/add {v}"),
   COUNT("Cups sold", 10, 10, 7, ("cup", "cups"), "the maker who sold {v}", "sold/sell {v}",
         "sold fewer cups than", "sold more cups than", "sold {dn} fewer cups than", "sold {dn} more cups than"),
   MONEY("Price", 1, 0.5, 7, "the maker who charged {v} a cup", "charged/charge {v} a cup", "charged less than",
         "charged more than", "charged {d} less than", "charged {d} more than"),
   N("Stand", ["by the school gate", "by the bakery", "on the corner", "by the bus stop", "by the post office", "by the library"],
     "the maker {v}", "set/set up {v}")]),

S("parcels", "neighbour",
  ["Parcels on Lantern Lane", "The Morning Post", "A Knock at the Door"],
  ["The post van stops at every door on Lantern Lane. Today {n} neighbours had a parcel.",
   "Brown paper, string and a knock at the door. {N} neighbours signed for a parcel this morning.",
   "Rosie the postwoman knows every door on the lane. Today she delivered to {n} of them."],
  [N("Parcel", ["seed catalogue", "knitting wool", "jigsaw", "teapot", "book", "scarf", "bird feeder"],
     "the neighbour who received the {v}", "received/receive the {v}"),
   TIME("Delivered", 600, 10, 8, "got the parcel", "got the parcel at", "get the parcel at"),
   COUNT("Weight", 1, 1, 7, ("lb", "lb"), "the neighbour whose parcel weighed {v}", "got/get a parcel weighing {v}",
         "got a lighter parcel than", "got a heavier parcel than", "got a parcel {d} lighter than", "got a parcel {d} heavier than"),
   N("Door", ["red door", "blue door", "green door", "yellow door", "black door", "white door"],
     "the neighbour with the {v}", "has the {v}")]),

S("bells", "ringer",
  ["The Bell Ringers", "Practice Night in the Tower", "Rounds and Call Changes"],
  ["Six bell ropes wait in the church tower, and every Wednesday the ringers climb the stairs. {N} ringers came this week.",
   "The tower stairs are steep and the bells are loud. {N} ringers practised their rounds tonight.",
   "When the bells ring out over Lantern Lane, everyone knows it's Wednesday. {N} ringers were on the ropes."],
  [N("Bell", ["treble", "second", "third", "fourth", "fifth", "tenor"],
     "the ringer on the {v} bell", "rang/ring the {v} bell"),
   COUNT("Years", 2, 2, 7, ("year", "years"), "the ringer with {v} in the tower", "has rung for {v}",
         "has rung for fewer years than", "has rung for more years than", "has rung {dn} years less than", "has rung {dn} years more than"),
   COUNT("Practices", 3, 1, 7, ("practice", "practices"), "the ringer who came to {v}", "came/come to {v}",
         "came to fewer practices than", "came to more practices than", "came to {dn} fewer practices than", "came to {dn} more practices than"),
   N("Street", STREETS, "the ringer from {v}", "walked/walk from {v}")]),

S("craftfair", "maker",
  ["The Winter Craft Fair", "Handmade in the Village Hall", "Stalls of Small Wonders"],
  ["The village hall turns into a craft fair on the first Saturday of December. {N} makers took a stall.",
   "Everything on the tables was made by hand. {N} makers sold their work to a busy crowd.",
   "Candles, carvings and a lot of glitter. {N} makers counted their sales at the end of the day."],
  [N("Craft", ["candles", "soap", "woodcarvings", "wreaths", "mittens", "bookmarks", "baskets"],
     "the maker who sold {v}", "sold/sell {v}"),
   MONEY("Earned", 40, 10, 7, "the maker who earned {v}", "earned/earn {v}", "earned less than", "earned more than",
         "earned {d} less than", "earned {d} more than"),
   N("Stall", ["by the stage", "near the door", "by the stairs", "by the tea urn", "under the clock", "by the window"],
     "the maker whose stall was {v}", "had/have a stall {v}"),
   TIME("Sold out", 660, 15, 8, "sold out", "sold out at", "sell out at")]),

S("play", "actor",
  ["The Village Play", "Rehearsal Night", "Lines, Please!"],
  ["The drama group is putting on a play about a lost lantern. {N} actors came to rehearsal on a snowy night.",
   "Scripts in hand, costumes half-finished. {N} actors rehearsed in the village hall.",
   "The director called for quiet. {N} actors took their places on the little stage."],
  [N("Role", ["the miller", "the queen", "the baker", "the owl", "the gardener", "the king", "the fox"],
     "the actor playing {v}", "played/play {v}"),
   COUNT("Lines", 10, 5, 7, ("line", "lines"), "the actor with {v}", "has {v}",
         "has fewer lines than", "has more lines than", "has {dn} fewer lines than", "has {dn} more lines than"),
   N("Prop", ["lantern", "teapot", "broom", "crown", "umbrella", "basket"],
     "the actor with the {v}", "carried/carry the {v}"),
   TIME("Arrived", 1080, 10, 8, "arrived", "arrived at", "arrive at")]),

S("apples", "picker",
  ["Apple Pressing Day", "The Cider Press", "Baskets of Russets"],
  ["Every October the old cider press comes out of the barn. {N} pickers brought apples to press.",
   "Crunch, squeeze, pour. {N} pickers took home bottles of fresh juice.",
   "The barn smelled of apples all day. {N} pickers lined up their baskets by the press."],
  [N("Apples", ["Bramley", "russet", "Cox", "Gala", "pippin", "Discovery", "Egremont"],
     "the picker who brought {v} apples", "brought/bring {v} apples"),
   COUNT("Bags", 2, 1, 7, ("bag", "bags"), "the picker who filled {v}", "filled/fill {v}",
         "filled fewer bags than", "filled more bags than", "filled {dn} fewer bags than", "filled {dn} more bags than"),
   COUNT("Bottles", 4, 2, 7, ("bottle", "bottles"), "the picker who took home {v}", "took/take home {v}",
         "took home fewer bottles than", "took home more bottles than", "took home {dn} fewer bottles than", "took home {dn} more bottles than"),
   N("Orchard", ["Hill Farm", "the vicarage", "Pear Tree Lane", "the old mill", "Glebe Cottage", "Rose Farm"],
     "the picker from {v}", "picked/pick at {v}")]),

S("hats", "buyer",
  ["The Hat Shop", "Ribbons and Brims", "Trying Them On"],
  ["Miss Lark's hat shop is the smallest shop on the lane. On Saturday {n} buyers each left with a hatbox.",
   "Mirrors on every wall and hats on every hook. {N} buyers found the perfect one.",
   "The bell over the hat shop door rang all day. {N} buyers chose a hat and a ribbon to go with it."],
  [N("Hat", ["cloche", "beret", "fedora", "trilby", "bonnet", "boater", "pillbox"],
     "the buyer who chose the {v}", "chose/choose the {v}"),
   MONEY("Price", 15, 5, 7, "the buyer who paid {v}", "paid/pay {v}", "paid less than", "paid more than",
         "paid {d} less than", "paid {d} more than"),
   N("Ribbon", ["plum ribbon", "teal ribbon", "gold ribbon", "scarlet ribbon", "ivory ribbon", "black ribbon"],
     "the buyer who picked the {v}", "picked/pick the {v}"),
   COUNT("Time in shop", 10, 10, 7, ("minute", "minutes"), "the buyer who stayed {v}", "stayed/stay {v}",
         "stayed a shorter time than", "stayed longer than", "stayed {d} less than", "stayed {d} longer than", label="{v} min")]),

S("film", "viewer",
  ["Film Night at the Village Hall", "The Old Projector", "Popcorn and a Black-and-White Film"],
  ["Once a month the village hall becomes a cinema. Tonight {n} viewers came to see an old comedy.",
   "The projector whirred and the lights went down. {N} viewers settled in with a snack.",
   "Rows of folding chairs, one big screen. {N} viewers came out on a cold night for the film."],
  [O("Row", "row", list(range(1, 8)), "the viewer in row {v}", "sat/sit in row {v}",
     "sat nearer the screen than", "sat farther from the screen than", "sat {d} nearer the screen than",
     "sat {d} farther back than", du=("row", "rows")),
   N("Snack", ["popcorn", "toffees", "humbugs", "fudge", "peanuts", "liquorice", "a choc ice"],
     "the viewer who had {v}", "had/have {v}"),
   TIME("Arrived", 1140, 5, 8, "arrived", "arrived at", "arrive at"),
   N("Coat", ["duffle coat", "raincoat", "parka", "tweed coat", "cape", "pea coat"],
     "the viewer in the {v}", "wore/wear the {v}")]),

S("railway", "modeller",
  ["The Model Railway Club", "Engines in the Loft", "All Aboard the Tiny Train"],
  ["The model railway club runs its layout in the loft above the post office. {N} modellers brought an engine on open day.",
   "Tiny tracks, tiny stations, very serious faces. {N} modellers ran their engines round the layout.",
   "Visitors crowded round the layout to watch. {N} engines went round, one for each modeller."],
  [N("Engine", ["The Comet", "Bluebell", "Puffin", "Duchess", "Lark", "Firefly", "Badger"],
     "the modeller who ran {v}", "ran/run {v}"),
   COUNT("Laps", 5, 1, 7, ("lap", "laps"), "the modeller whose engine ran {v}", "ran/run {v} without stopping",
         "ran fewer laps than", "ran more laps than", "ran {dn} fewer laps than", "ran {dn} more laps than"),
   COUNT("Wagons", 2, 1, 7, ("wagon", "wagons"), "the modeller who attached {v}", "attached/attach {v}",
         "attached fewer wagons than", "attached more wagons than", "attached {dn} fewer wagons than", "attached {dn} more wagons than"),
   N("Colour", ["green", "maroon", "black", "blue", "red", "brown"],
     "the modeller with the {v} engine", "painted/paint the engine {v}")]),

S("recital", "pupil",
  ["The Winter Piano Recital", "Scales and Waltzes", "A Bow at the End"],
  ["Mrs Penrose's front room was full of parents for the winter recital. {N} pupils played one piece each.",
   "Polished shoes, nervous smiles. {N} pupils took turns at the old upright piano.",
   "Applause, a bow and a biscuit afterwards. {N} pupils played at the winter recital."],
  [N("Piece", ["waltz", "march", "lullaby", "minuet", "nocturne", "sonatina", "jig"],
     "the pupil who played the {v}", "played/play the {v}"),
   ORDINAL("Turn", 6, "the pupil who went {v}", "went/go {v}", "went before", "went after",
           "went {d} before", "went {d} after", du=("turn", "turns")),
   PLAIN("Age", 7, 1, 7, ("year", "years"), "the pupil aged {v}", "is {v} years old",
         "is younger than", "is older than", "is {d} younger than", "is {d} older than"),
   N("Teacher", ["Miss Gray", "Mr Hale", "Mrs Penn", "Mr Lowe", "Miss Fry", "Mrs Dale"],
     "the pupil taught by {v}", "is taught by {v}")]),

S("windows", "cottage",
  ["The Window Contest", "Lights in Every Window", "Candles on the Sills"],
  ["Every winter the cottages on Lantern Lane compete for the best-lit window. {N} cottages entered this year.",
   "Walk down the lane after dark and every window glows. The judges scored {n} of them.",
   "The judges walked the lane with a lantern and a notebook. {N} cottages hoped for the prize."],
  [N("Display", ["paper stars", "a row of candles", "lanterns", "fairy lights", "snowflakes", "pine boughs"],
     "the cottage with {v}", "showed/show {v}"),
   COUNT("Score", 5, 1, 6, ("point", "points"), "the cottage that scored {v}", "scored/score {v}",
         "scored fewer points than", "scored more points than", "scored {dn} fewer points than", "scored {dn} more points than"),
   N("Owner", PEOPLE[30:], "the cottage that belongs to {v}", "~belongs/belong to {v}"),
   COUNT("Hours lit", 3, 1, 7, ("hour", "hours"), "the cottage lit for {v}", "stayed/stay lit for {v}",
         "stayed lit for less time than", "stayed lit longer than", "stayed lit {d} less than", "stayed lit {d} longer than")],
  key="Cottage", keypool=COTTAGES, keytense="is"),

S("toys", "owner",
  ["The Toy Hospital", "Mended While You Wait", "Stitches for Teddy"],
  ["On the first Saturday of the month, two retired engineers run a toy hospital in the library. {N} young owners brought a toy.",
   "Glue, thread and a tiny screwdriver. {N} children waited while their toys were mended.",
   "Every toy left the toy hospital as good as new. {N} owners were very pleased."],
  [N("Toy", ["teddy bear", "rag doll", "wooden train", "rocking horse", "spinning top", "jack-in-the-box", "toy drum"],
     "the owner of the {v}", "brought/bring the {v}"),
   N("Repair", ["a new eye", "stitches", "a new wheel", "fresh paint", "a new spring", "new string"],
     "the owner whose toy needed {v}", "brought/bring a toy that needed {v}"),
   PLAIN("Age", 4, 1, 7, ("year", "years"), "the owner aged {v}", "is {v} years old",
         "is younger than", "is older than", "is {d} younger than", "is {d} older than"),
   COUNT("Wait", 5, 5, 7, ("minute", "minutes"), "the owner who waited {v}", "waited/wait {v}",
         "waited less time than", "waited longer than", "waited {d} less than", "waited {d} longer than", label="{v} min")]),

S("jam", "maker",
  ["The Jam Judging", "Jars on the Long Table", "A Spoonful for the Judge"],
  ["The jam class is the most hotly contested at the village show. {N} makers entered this year.",
   "The judge held each jar to the light before she tasted it. {N} makers waited nervously.",
   "Shiny jars with paper labels lined the long table. {N} makers hoped for a rosette."],
  [N("Jam", ["strawberry", "damson", "gooseberry", "plum", "apricot", "blackcurrant", "quince"],
     "the maker of the {v} jam", "made/make {v} jam"),
   COUNT("Jars", 1, 1, 7, ("jar", "jars"), "the maker who entered {v}", "entered/enter {v}",
         "entered fewer jars than", "entered more jars than", "entered {dn} fewer jars than", "entered {dn} more jars than"),
   COUNT("Score", 5, 1, 6, ("point", "points"), "the maker who scored {v}", "scored/score {v}",
         "scored fewer points than", "scored more points than", "scored {dn} fewer points than", "scored {dn} more points than"),
   N("Lid", ["gingham lid", "gold lid", "red lid", "paper cap", "wax seal", "cork"],
     "the maker who used the {v}", "used/use the {v}")]),

S("crossword", "solver",
  ["The Crossword Race", "Seven Across", "Pencils at the Ready"],
  ["Every Sunday the café holds a crossword race. This week {n} solvers finished the puzzle.",
   "One crossword, one clock, a lot of furrowed brows. {N} solvers raced to the last clue.",
   "The café owner prints the puzzle and starts the clock. {N} solvers finished before the coffee went cold."],
  [COUNT("Time", 12, 3, 7, ("minute", "minutes"), "the solver who took {v}", "took/take {v}",
         "finished faster than", "took longer than", "finished {d} faster than", "took {d} longer than", label="{v} min"),
   N("Pen", ["fountain pen", "pencil", "biro", "felt pen", "gel pen", "crayon"],
     "the solver using the {v}", "used/use the {v}"),
   N("Pastry", ["croissant", "muffin", "scone", "danish", "crumpet", "flapjack"],
     "the solver who ate a {v}", "ate/eat a {v}"),
   N("Seat", ["by the window", "at the counter", "by the fire", "at the long table", "in the corner", "by the door"],
     "the solver {v}", "sat/sit {v}")]),

S("firewood", "customer",
  ["Firewood for the Winter", "The Log Man's Round", "Stacked by the Back Door"],
  ["When the nights draw in, the log man's lorry goes up and down the lane. This week he delivered to {n} customers.",
   "Nothing warms a cottage like a proper log fire. {N} customers ordered wood this week.",
   "The log man writes everything in a little book. This week's page shows {n} customers."],
  [N("Wood", ["oak", "ash", "birch", "beech", "applewood", "cherry", "hawthorn"],
     "the customer who ordered {v}", "ordered/order {v}"),
   COUNT("Bundles", 2, 1, 7, ("bundle", "bundles"), "the customer who got {v}", "got/get {v}",
         "got fewer bundles than", "got more bundles than", "got {dn} fewer bundles than", "got {dn} more bundles than"),
   O("Day", "day", list(range(6)), "the customer whose wood came on {v}", "got/get the wood on {v}",
     "got the wood earlier in the week than", "got the wood later in the week than",
     "got the wood {d} before", "got the wood {d} after", du=("day", "days")),
   MONEY("Price", 20, 5, 7, "the customer who paid {v}", "paid/pay {v}", "paid less than", "paid more than",
         "paid {d} less than", "paid {d} more than")]),

S("bookclub", "member",
  ["The Book Club", "Chapter and Verse", "Tea and Classics"],
  ["The book club meets above the bakery, which explains the snacks. {N} members came this month.",
   "This month's book was long, and not everyone finished it. {N} members met to talk it over.",
   "Armchairs, lamplight and opinions. {N} book club members gathered by the fire."],
  [N("Author", ["Austen", "Dickens", "Bronte", "Eliot", "Hardy", "Gaskell", "Trollope"],
     "the member who prefers {v}", "~prefers/prefer {v}"),
   COUNT("Pages read", 50, 50, 7, ("page", "pages"), "the member who read {v}", "read/read {v}",
         "read fewer pages than", "read more pages than", "read {dn} fewer pages than", "read {dn} more pages than"),
   N("Snack", ["lemon bars", "cheese straws", "ginger snaps", "almond biscuits", "fruit loaf", "flapjacks"],
     "the member who brought the {v}", "brought/bring the {v}"),
   COUNT("Membership", 1, 1, 7, ("year", "years"), "the member of {v}", "has been a member for {v}",
         "has been a member for less time than", "has been a member longer than",
         "has been a member {d} less than", "has been a member {d} longer than")]),

S("tidyup", "volunteer",
  ["The Village Tidy-Up", "Many Hands", "Brooms and Paintbrushes"],
  ["On the first dry Saturday of spring, volunteers spruce up the village. {N} of them turned out this year.",
   "Gloves on, sleeves up. {N} volunteers spent the morning making the village shine.",
   "The parish clerk handed out jobs from a clipboard. {N} volunteers each took one."],
  [N("Job", ["sweeping paths", "painting railings", "clearing leaves", "planting bulbs", "fixing fences", "washing signs"],
     "the volunteer who was {v}", "was {v}"),
   COUNT("Hours", 1, 1, 7, ("hour", "hours"), "the volunteer who worked {v}", "worked/work {v}",
         "worked fewer hours than", "worked more hours than", "worked {dn} fewer hours than", "worked {dn} more hours than"),
   N("Tool", ["rake", "broom", "trowel", "paintbrush", "hammer", "bucket", "shears"],
     "the volunteer with the {v}", "used/use the {v}"),
   TIME("Started", 480, 30, 7, "started", "started at", "start at")]),

S("ramble", "rambler",
  ["The Winter Ramble", "Over the Stiles", "Muddy Boots"],
  ["The ramblers' club walks every Sunday whatever the weather. This week {n} ramblers set off from the green.",
   "Frost on the fields, mud on the boots. {N} ramblers each chose their own route.",
   "Map, flask and a sandwich. {N} ramblers walked the footpaths around the village."],
  [COUNT("Distance", 3, 1, 7, ("mile", "miles"), "the rambler who walked {v}", "walked/walk {v}",
         "walked a shorter way than", "walked farther than", "walked {d} less than", "walked {d} farther than"),
   N("Lunch", ["cheese rolls", "a pasty", "soup", "egg sandwiches", "oatcakes", "fruitcake"],
     "the rambler who packed {v}", "packed/pack {v}"),
   N("Stick", ["hazel stick", "ash stick", "blackthorn", "walking poles", "umbrella", "crook"],
     "the rambler with the {v}", "carried/carry the {v}"),
   TIME("Finished", 780, 10, 8, "finished", "finished at", "finish at")]),
]

# The worked example uses its own small scene so it doesn't repeat a puzzle.
EXAMPLE = S("mittens", "child",
  ["The Lost Mittens", "-", "-"],
  ["Four children lost a mitten on the way home from school. The lollipop lady found them all and pegged them on her line.", "-", "-"],
  [N("Mitten", ["red mitten", "blue mitten", "green mitten", "yellow mitten"], "the child who lost the {v}", "lost/lose the {v}"),
   TIME("Collected", 930, 15, 4, "collected it", "collected it at", "collect it at"),
   N("Peg", ["wooden peg", "plastic peg", "metal clip", "clothes pin"], "the child whose mitten hung on the {v}", "found/find it on the {v}"),
   N("Hat", ["bobble hat", "beanie", "hood", "earmuffs"], "the child in the {v}", "wore/wear the {v}")])
