"""Picture subjects (glyph from the monochrome Noto Emoji font, SIL OFL) and the name printed
with each solution. Cozy, winter-friendly, non-violent, nothing Christmas-specific, no people."""
SUBJECTS = [
 ("☕", "A Cup of Cocoa"), ("🫖", "The Teapot"), ("❄", "A Snowflake"), ("⛄", "A Snowman"),
 ("🌲", "A Pine Tree"), ("🏔", "The Mountain"), ("🦉", "An Owl"), ("🦊", "A Fox"),
 ("🐇", "A Snow Hare"), ("🦌", "A Deer"), ("🐧", "A Penguin"), ("🐿", "A Squirrel"),
 ("🦔", "A Hedgehog"), ("🐦", "A Little Bird"), ("🕯", "A Candle"), ("🏮", "A Paper Lantern"),
 ("🧣", "A Scarf"), ("🧤", "Mittens"), ("🥾", "A Hiking Boot"), ("⛸", "An Ice Skate"),
 ("🛷", "A Sled"), ("🎿", "Skis"), ("🏠", "A Cottage"), ("🛖", "A Snowy Hut"),
 ("🚂", "The Steam Engine"), ("🌙", "The Crescent Moon"), ("⭐", "A Star"), ("🔭", "The Telescope"),
 ("📚", "A Stack of Books"), ("📖", "An Open Book"), ("🔑", "A Key"), ("🕰", "The Mantel Clock"),
 ("🧶", "A Ball of Yarn"), ("🍪", "A Cookie"), ("🥧", "A Pie"), ("🍞", "A Loaf of Bread"),
 ("🥐", "A Croissant"), ("🍯", "A Honey Pot"), ("🍎", "An Apple"), ("🍄", "A Mushroom"),
 ("🍂", "Fallen Leaves"), ("🔥", "A Crackling Fire"), ("🪶", "A Feather"), ("🦢", "A Swan"),
 ("🐈", "A Cat"), ("🐕", "A Dog"), ("🐑", "A Sheep"), ("🧸", "A Teddy Bear"),
 ("🎻", "A Violin"), ("🧩", "A Jigsaw Piece"), ("♟", "A Chess Pawn"), ("✏", "A Pencil"),
 ("🧭", "A Compass"), ("⛺", "A Tent"), ("🏕", "A Campsite"), ("🚠", "The Cable Car"),
 ("🌨", "A Snow Cloud"), ("🧊", "An Ice Cube"), ("🪟", "A Window"), ("🛋", "The Sofa"),
 ("🪑", "A Chair"), ("🧦", "Warm Socks"), ("👢", "A Winter Boot"), ("🦭", "A Seal"),
 ("🐟", "A Fish"), ("🦦", "An Otter"), ("🐭", "A Mouse"), ("🍵", "A Cup of Tea"),
 ("🧁", "A Cupcake"), ("🍩", "A Doughnut"), ("🥨", "A Pretzel"), ("🧀", "A Wedge of Cheese"),
 ("🥕", "A Carrot"), ("🫕", "A Fondue Pot"), ("🎩", "A Top Hat"), ("☂", "An Umbrella"),
 ("🪴", "A Potted Plant"), ("🐴", "A Horse"),
 ("🐻", "A Bear"), ("🐼", "A Panda"), ("🐨", "A Koala"), ("🐰", "A Bunny"), ("🐱", "A Kitten"),
 ("🐶", "A Puppy"), ("🐺", "A Wolf"), ("🦝", "A Raccoon"), ("🦫", "A Beaver"), ("🦡", "A Badger"),
 ("🐾", "Paw Prints"), ("🦆", "A Duck"), ("🦅", "An Eagle"), ("🕊", "A Dove"), ("🐓", "A Rooster"),
 ("🐐", "A Goat"), ("🐄", "A Cow"), ("🐖", "A Pig"), ("🐢", "A Tortoise"), ("🐌", "A Snail"),
 ("🦋", "A Butterfly"), ("🐝", "A Bee"), ("🐞", "A Ladybird"), ("🐋", "A Whale"), ("🐬", "A Dolphin"),
 ("🐳", "A Spouting Whale"), ("🦀", "A Crab"), ("🐙", "An Octopus"), ("🐘", "An Elephant"), ("🦒", "A Giraffe"),
 ("🦘", "A Kangaroo"), ("🦙", "A Llama"), ("🦬", "A Bison"), ("🫎", "A Moose"), ("🐫", "A Camel"),
 ("🌳", "An Oak Tree"), ("🌰", "A Chestnut"), ("🍁", "A Maple Leaf"), ("🌻", "A Sunflower"), ("🌷", "A Tulip"),
 ("🌵", "A Cactus"), ("🍐", "A Pear"), ("🍋", "A Lemon"), ("🍊", "An Orange"), ("🍓", "A Strawberry"),
 ("🍒", "Cherries"), ("🍇", "Grapes"), ("🥥", "A Coconut"), ("🥑", "An Avocado"), ("🌽", "An Ear of Corn"),
 ("🥖", "A Baguette"), ("🧇", "A Waffle"), ("🥞", "Pancakes"), ("🍰", "A Slice of Cake"), ("🎂", "A Cake"),
 ("🍫", "A Chocolate Bar"), ("🍬", "A Sweet"), ("🍭", "A Lollipop"), ("🍮", "A Pudding"), ("🥛", "A Glass of Milk"),
 ("🍲", "A Pot of Stew"), ("🥣", "A Bowl of Porridge"), ("🥄", "A Spoon"), ("🫙", "A Jar"), ("🧂", "The Salt Shaker"),
 ("🎈", "A Balloon"), ("🪁", "A Kite"), ("🧵", "A Spool of Thread"), ("🪡", "A Sewing Needle"), ("🧺", "A Basket"),
 ("🪣", "A Bucket"), ("🧹", "A Broom"), ("🪜", "A Ladder"), ("🛁", "A Bathtub"), ("🛏", "A Bed"),
 ("🚪", "A Door"), ("🪞", "A Mirror"), ("🖼", "A Framed Picture"), ("💡", "A Light Bulb"), ("🔦", "A Flashlight"),
 ("🎹", "A Piano"), ("🎺", "A Trumpet"), ("🎷", "A Saxophone"), ("🪕", "A Banjo"), ("🥁", "A Drum"),
 ("🎵", "A Musical Note"), ("📷", "A Camera"), ("📻", "A Radio"), ("☎", "A Telephone"), ("⌛", "An Hourglass"),
 ("⏰", "An Alarm Clock"), ("✉", "An Envelope"), ("📮", "A Postbox"), ("🖋", "A Fountain Pen"), ("📌", "A Pushpin"),
 ("✂", "Scissors"), ("📎", "A Paper Clip"), ("🔍", "A Magnifying Glass"), ("🗝", "An Old Key"), ("🎲", "A Die"),
 ("🎳", "Bowling"), ("🪀", "A Yo-yo"), ("⚓", "An Anchor"), ("⛵", "A Sailboat"), ("🚲", "A Bicycle"),
 ("🚗", "A Car"), ("🚌", "A Bus"), ("🚜", "A Tractor"), ("🚁", "A Helicopter"), ("✈", "An Aeroplane"),
 ("🚀", "A Rocket"), ("🛸", "A Flying Saucer"), ("🎡", "A Ferris Wheel"), ("🏰", "A Castle"), ("⛪", "A Chapel"),
 ("🏡", "A House and Garden"), ("🏚", "An Old Cabin"), ("⛲", "A Fountain"), ("🌉", "A Bridge at Night"), ("🗻", "A Snowy Peak"),
 ("☁", "A Cloud"), ("☀", "The Sun"), ("🌈", "A Rainbow"), ("☃", "A Snowman in the Snow"), ("💧", "A Droplet"),
 ("🌊", "A Wave"), ("🌍", "The Globe"), ("🪐", "A Ringed Planet"), ("🌟", "A Glowing Star"), ("🌛", "The Moon's Face"),
 ("👓", "Spectacles"), ("🎒", "A Rucksack"), ("👜", "A Handbag"), ("🧢", "A Cap"), ("👒", "A Sun Hat"),
 ("🥿", "A Slipper"), ("👕", "A T-shirt"), ("🧥", "A Coat"), ("👗", "A Dress"), ("💍", "A Ring"),
 ("💎", "A Gem"), ("🔔", "A Bell"), ("🧲", "A Magnet"), ("🔋", "A Battery"), ("⚙", "A Gear"),
 ("🧪", "A Test Tube"), ("🔬", "A Microscope"), ("🛎", "A Desk Bell"), ("🧳", "A Suitcase"), ("🌂", "A Closed Umbrella"),
 ("🎨", "A Paint Palette"), ("🖌", "A Paintbrush"), ("🖍", "A Crayon"), ("📐", "A Set Square"), ("📏", "A Ruler"),
]
