# Narrative and instruction text for The Advent Clock. Nobody is hurt, nothing violent happens.
PROLOGUE = [
 "Every December since 1926, the Great Advent Clock has stood in the lobby of the Snowberry Lodge, between the fireplace and the stairs: a tall case of dark walnut with a painted moon on its face and, below the face, twenty-four little doors, each no bigger than a playing card.",
 "It was built by the village clockmaker, Barnaby Thrush, and it has been looked after ever since by his granddaughter, Mrs. Ottilie Thrush, who is eighty-one, wears three cardigans at once, and knows more about puzzles than anyone on the mountain.",
 "The tradition is simple. On the first of December Ottilie hides the lodge’s silver star, the one that goes on top of the great tree in the lobby, and the twenty-four little doors hold the clues to where it is. Each door has a tiny brass dial of letters. Dial the right word and the door springs open.",
 "This year Ottilie has gone to spend Christmas with her sister by the sea. She has left the manager, Mr. Humphrey Budd, a sealed envelope, a notebook of twenty-four puzzles, and strict instructions: <i>one door a day, no peeking, and the star goes on the tree at midnight on Christmas Eve.</i>",
 "Mr. Budd, who is round and kind and hopeless at puzzles, has handed the notebook to you. His niece Winnie, fifteen and never without her detective’s notebook, has appointed herself your assistant. Nobody has dared to argue.",
]
LETTER = [
 "My dear puzzler,",
 "Behind the doors of my grandfather’s clock you will find twenty-four puzzles, one for every day of Advent. Each one hides a single word. Dial it, and the door will open.",
 "Each word also gives you one letter, its <b>key letter</b>, which I have marked. Keep all twenty-four safe in the Door Log. On Christmas Eve they will tell you where I have hidden the star.",
 "Take your time, drink plenty of cocoa, and don’t let Humphrey near the gingerbread.",
 "With love and a merry Christmas,",
 "<i>Ottilie Thrush</i>",
]
HOWTO = [
 ("One door a day.", "Each door has two facing pages: a short scene and the rules on the left, the puzzle on the right. You can of course go at your own speed; the puzzles do not depend on each other until Christmas Eve."),
 ("Find the word.", "Every puzzle leads to exactly one answer word. The rules tell you how to read it out of the finished puzzle. Write it in the answer boxes."),
 ("Keep the key letter.", "One answer box is drawn with a heavy border and a small key. That is the day’s <b>key letter</b>. Copy it into the Door Log on page {log}."),
 ("Stuck?", "Every door has three hints at the back of the book, in three separate sections so you only see as much as you want: a <b>Nudge</b>, a <b>Foothold</b> and a <b>Last Step</b>. Full solutions come after the hints."),
 ("Checked by computer.", "Every grid puzzle in this book was re-solved by a separate computer program to make sure it has exactly one solution, and every answer was checked letter by letter."),
 ("You will need", "a pencil, an eraser, and on one or two days a little patience. No phone, app or internet is needed."),
]

DOORS = {
 1: ("The First Door", "Ottilie’s notebook is bound in green cloth and smells of pine needles. The first page says only: <i>Start with something easy. Everybody deserves a warm-up.</i> Winnie reads it over your shoulder, sharpens two pencils, and hands you one. Outside, the first proper snow of the winter is settling on the car park, and in the kitchen someone is already melting chocolate. Door One is the lowest on the left, with a sprig of painted holly around its keyhole.", "Find every word from the list in the grid. Words run {dirs}, and they may share letters. When all the words are found, read the letters that were not used, row by row from the top left. They spell a short message."),
 2: ("A Secret Message", "Behind the first door you found a tiny wooden sleigh, painted red. Today the notebook holds a line of nonsense letters and a note: <i>Grandfather liked to move things along a little. Every letter here has taken the same number of steps along the alphabet, fewer than five.</i> Winnie is certain it is a code used by Roman generals. Mr. Budd is certain it is a shopping list. They are both a little bit right.", "Each letter of the message has been shifted forward along the alphabet by the same number of steps (after Z comes A again). Shift every letter back by that number to read the message. Try each number from 1 to 4 on the first word: only one gives English."),
 3: ("Stars in the Garden", "The lodge garden is a patchwork of flowerbeds under the snow, and Ottilie has drawn a map of them in the notebook: six beds, oddly shaped, fitted together like a quilt. <i>Every spring I plant one silver star in each bed,</i> she writes, <i>and in each row and each column, and never two side by side, because stars need room to shine.</i>", "Place six stars in the grid: exactly one in each row, one in each column and one in each outlined region. No two stars may touch, not even diagonally. When all the stars are placed, read the small letters under them, row by row from the top."),
 4: ("The Sleigh Puzzle", "In the old stables behind the lodge stands the sleigh that used to carry guests up from the village before the railway came. Its seat is carved with a square of letters, and some of the letters have worn away. Winnie brushes off the snow and copies what is left into the notebook. <i>Six letters,</i> she says, <i>and they’re all in every row.</i>", "Fill the grid so that every row, every column and every 2×3 box contains each of the six letters {syms} exactly once. Then read the letters in the numbered cells, in number order: 1, 2, 3 and so on."),
 5: ("The Toboggan Run", "On the fifth morning the snow is perfect, and half the lodge is out on the hill with toboggans. Ottilie’s puzzle is a map of the old run through the pine wood, which twists back on itself so often that Mr. Budd once got lost on it for an entire afternoon. <i>Keep to the path,</i> the note says, <i>and collect the letters as you go.</i>", "Find the way through the maze from the entrance at the top left to the exit at the bottom right. There is only one route. Some squares hold letters: the ones on your route, read in the order you pass them, spell the answer. Letters off the route are decoys."),
 6: ("A Picture in the Dark", "A storm brings the power lines down, and the lodge spends the evening by firelight. Mr. Budd hands round blankets; somebody starts a sing-song in the lounge. Winnie holds a flashlight while you open the notebook to a page of numbers with no picture at all. <i>Shade the right squares,</i> Ottilie has written, <i>and you will see what we need tonight.</i>", "Shade some squares of the grid to reveal a picture. The numbers beside each row and above each column give the lengths of the runs of shaded squares in that line, in order, with at least one blank square between runs. The picture names the answer."),
 7: ("The Snowball Stack", "The annual snowball-building contest is held on the front lawn. The rule is ancient and very strict: every snowball in a stack must weigh exactly as much as the two it sits on. Ottilie has drawn last year’s winning stack, with most of the numbers rubbed out, and a line at the bottom: <i>A = 1, B = 2 … Z = 26.</i>", "Each brick in the pyramid holds the sum of the two bricks directly below it. Work out every number. Then turn the five numbers in the bottom row into letters with A = 1, B = 2, and so on up to Z = 26, and read them from left to right."),
 8: ("The Pigpen Code", "Winnie has discovered that the old pantry door is covered, at knee height, in strange scratched symbols: little corners, boxes and arrows, some with dots. The cook says they have always been there. The notebook says: <i>Grandfather’s favourite code. It fits in a noughts-and-crosses grid, and it has kept the pantry secret for a hundred years.</i>", "Each symbol stands for one letter. The key shows how: a letter is drawn as the shape of the part of the grid it sits in, with a dot if it comes from a dotted grid. Decode the message, one symbol at a time."),
 9: ("Five Skaters", "Five guests from the corridor on the second floor have gone skating on the frozen lake, and they have all left their mugs of cocoa on the windowsill of the boathouse. The notebook sets you a proper old-fashioned logic puzzle about them. <i>When you know who sleeps where,</i> writes Ottilie, <i>walk down the corridor from Room 1 and say their names.</i>", "Rooms 1 to 5 are in a row along the corridor, from left to right. Each of the five guests has a different room, a different topping on their cocoa and has knitted a different thing. Use the clues and the chart to match everything up. Then read the first letters of the guests’ names in room order, 1 to 5."),
 10: ("Snowmen and Pines", "The children of the lodge have built snowmen all over the pine grove, one for each tree, and they want a plan of it for the lodge newsletter. The snowmen are shy, apparently: they will not stand next to one another, even corner to corner. Winnie has been appointed Chief Snowman Surveyor.", "Place one snowman next to each pine tree, directly above, below, left or right of it. Every tree has its own snowman. No two snowmen touch, not even diagonally. The numbers show how many snowmen are in each row and column. Then read the small letters under the snowmen, row by row from the top."),
 11: ("The Little Railway", "The little mountain train is running late, as usual, because of the snow, and the children have built their own railway in the lobby out of cardboard. Ottilie’s puzzle is a tiny railway too. <i>Lay the line,</i> she writes, <i>and read the station names on the way.</i>", "Draw one continuous track that enters at A and leaves at B. The track goes through square centres, with straight pieces and curves only; it never branches or crosses itself. The numbers tell you how many squares in each row and column hold track. Some pieces are laid for you. Read the letters on the track, in order from A to B."),
 12: ("Lanterns in the Cellar", "The lodge cellar is a maze of brick pillars and wine racks, and it needs lighting for the Christmas party. Every lantern lights its own square and shines along its row and column until it hits a wall. Two lanterns that can see each other dazzle each other, which Ottilie will not allow.", "Place lanterns in some white squares so that every white square is lit. A lantern lights its square and every square in its row and column until a black block stops it. No lantern may shine on another. A number on a black block tells you how many lanterns are directly next to it (above, below, left, right). Read the letters under the lanterns, row by row from the top."),
 13: ("By the Hearth", "The big fireplace in the lounge has a basket of logs, a basket of knitting, and today a basket of words. Ottilie has left a list of Christmassy things and a blank grid, like a crossword with no clues. <i>Everything fits in just one way,</i> she writes. <i>And then sit by the fire for a while.</i>", "Fit every word from the list into the grid, one letter per white square, reading across or down. Each word is used once. Use the lengths and the crossing letters to decide which word goes where. Then read the letters in the numbered circles, in number order."),
 14: ("Hidden Presents", "Mr. Budd has hidden presents for the staff around the storeroom, and forgotten where. All he remembers is how many presents were near each spot on the floor. Winnie rolls her eyes and fetches the notebook.", "Some squares hide a present. A number in a square tells you how many presents are in the up to eight squares around it (including diagonals); squares with numbers never hide a present. There are exactly {total} presents. Find them all, then read the letters in their squares, row by row from the top."),
 15: ("The Bauble Tree", "The tree in the lobby is still bare at the top, waiting for its star, but the lower branches are filling up with glass baubles from a battered old box. Each bauble has a number painted on it. Ottilie’s puzzle arranges them in a square and asks you to put them in order.", "Fill the grid with the numbers 1 to 5 so that each number appears once in every row and every column. The signs between squares point to the smaller number (&lt; and &gt;). Then turn the digits in the numbered cells into letters with the key, and read them in number order."),
 16: ("Bells on the Sleigh", "On the sixteenth, the sleigh from Door Four is out on the snow again, pulled by two very patient ponies, and its bells ring out across the valley: short and long, short and long. <i>Listen carefully,</i> the notebook says, <i>they are telling you what goes in the cocoa tonight.</i>", "The message is written in Morse code: each letter is a group of dots (short rings) and dashes (long rings). Letters are separated by spaces and words by a slash. Use the table to decode it."),
 17: ("The Sleigh Fleet", "Every year on the seventeenth the whole valley holds a sleigh race, and the frozen lake becomes a car park for sleighs. Ottilie has drawn a map of the lake from memory, with the sleighs parked neatly so that none of them touch, as the rules demand.", "Hide the fleet in the grid: one sleigh of three squares, two of two squares and three little sleds of one square. Each lies across or down. No two touch, not even diagonally. The numbers show how many squares are taken in each row and column. Some squares are marked as open snow ({snow}) or sleigh ({ship}). Read the letters in the sleighs’ squares, row by row."),
 18: ("The Lantern Walk", "Tonight is the lantern walk through the woods, and the lobby is full of guests in boots and scarves arguing about who has the matches. Ottilie’s puzzle is a bigger word search, and a trickier one. <i>My words hide in every direction,</i> she warns, <i>even backwards, like my nephew.</i>", "Find every word from the list in the grid. Words run {dirs}, and they may share letters. When all the words are found, read the letters that were not used, row by row from the top left. They spell a short message."),
 19: ("Chimneys", "From the top of the hill behind the lodge you can see all the chimneys of the village, puffing away. Some are tall, some are short, and the tall ones hide the short ones behind them. Ottilie’s puzzle is a village of chimneys seen from all four sides.", "Fill the grid with chimneys of height 1 to 5, each height once in every row and column. A number outside the grid tells you how many chimneys you can see from that side, looking along the row or column: a taller chimney hides every shorter one behind it. Then turn the digits in the numbered cells into letters with the key, and read them in number order."),
 20: ("A Snowball Fight", "The great snowball fight between the kitchen staff and the guests ends, as it does every year, in a draw and hot cocoa. On the notebook page, Ottilie has drawn the battlefield: the lodge lawn, divided into eight patches, with room for one snow fort in each.", "Place eight stars in the grid: exactly one in each row, one in each column and one in each outlined region. No two stars may touch, not even diagonally. When all the stars are placed, read the small letters under them, row by row from the top."),
 21: ("The Bell Tower", "At noon, the bell in the little tower above the lodge rings for the midwinter lunch, and everyone troops in from the snow. Winnie notices that it rings twenty-one times, not twelve. <i>Someone has been fiddling with the clockwork,</i> she says darkly. The notebook just has another page of numbers.", "Shade some squares of the grid to reveal a picture. The numbers beside each row and above each column give the lengths of the runs of shaded squares in that line, in order, with at least one blank square between runs. The picture names the answer."),
 22: ("Cookie Tins", "The kitchen is in full Christmas baking mode, and every surface is covered in cookie tins. Each tin has a label with a number and a little sum: the cook’s own system, which nobody else understands. Winnie thinks it is a code. It is, of course, a puzzle.", "Fill the grid with the numbers 1 to 5 so that each number appears once in every row and every column. Each outlined tin shows a target and a sign: the numbers in the tin must make the target with that sign (+ add, × multiply, − difference, ÷ division, in any order). A tin with no sign is just that number. Then turn the digits in the numbered cells into letters with the key, and read them in number order."),
 23: ("The Big Bake", "The day before Christmas Eve is the day of the Big Bake. The cook’s great fruitcake has been soaking in something strong since October, and the whole lodge smells of oranges and spice. Ottilie’s last big puzzle is a full-size letter square, nine by nine.", "Fill the grid so that every row, every column and every 3×3 box contains each of the nine letters {syms} exactly once. Then read the letters in the numbered cells, in number order."),
 24: ("The Last Line", "Christmas Eve. The lodge is full, the snow is falling, and the tree in the lobby is covered from top to bottom, except for the very top. At four in the afternoon Mr. Budd starts pacing. At five, Winnie confiscates his cocoa. There is one door left, and one last railway to lay.", "Draw one continuous track that enters at A and leaves at B. The track goes through square centres, with straight pieces and curves only; it never branches or crosses itself. The numbers tell you how many squares in each row and column hold track. Some pieces are laid for you. Read the letters on the track, in order from A to B."),
}

NUDGE = {
 "wordsearch": "Start with the longest words and the rare letters (K, W, Y). Cross each word off the list and lightly shade its letters.",
 "caesar": "Look at the short words: a three-letter word that appears twice is very likely THE.",
 "queens": "Find the smallest region first: its star has only a few places to go. Then rule out every square that touches a placed star.",
 "wordoku": "Look for a row, column or box that already has most of its letters. The missing letters can often go in only one place.",
 "maze": "Try working backwards from the exit, and shade dead ends as you find them.",
 "nonogram": "Start with the biggest numbers. A run of 13 in a line of 15 must cover the middle 11 squares, wherever it starts.",
 "pyramid": "Look for a brick whose two neighbours in the triangle are already known: a brick below = the brick above minus its partner.",
 "pigpen": "Every symbol is either a piece of a # grid or a piece of an X. Match the shape first, then look for the dot.",
 "logic": "Mark each clue in the chart with ✗ for impossible and ● for certain. When a row has four ✗, the fifth square is certain.",
 "tents": "Rows and columns with a 0 have no snowmen: rule them out first. A tree with only one free neighbour must have its snowman there.",
 "tracks": "A row or column with the number of the grid’s width is full. Near A and B, the track has only a few ways to go.",
 "akari": "Blocks with a 4, or with a 3 against an edge, force their lanterns at once. A 0 means no lanterns next to it.",
 "presents": "A 0 means all its neighbours are safe. Where a number has exactly as many hidden neighbours as its value, all of them are presents.",
 "futoshiki": "A 5 can never be smaller than anything, and a 1 can never be larger. Follow chains of signs: in a < b < c, a is at most 3.",
 "morse": "The single dot is E and the single dash is T; the table shows the rest. Split each group at the spaces.",
 "fleet": "Rows and columns with a 0 are open snow. Put the three-square sleigh first: it only fits where a row or column number is 3 or more.",
 "skyscrapers": "A 1 means the tallest chimney (5) is right next to that edge. A 5 means the chimneys rise 1, 2, 3, 4, 5 from that edge.",
 "calcudoku": "Start with one-square tins and small cages with a large product or a big difference: they allow very few pairs.",
 "fillin": "Count the words of each length. A length with only one word tells you exactly where that word goes.",
}
EPILOGUE = [
 "At a quarter to midnight the whole lodge crowds into the lobby. Winnie leads the way up the narrow stairs behind the Great Advent Clock, into the little clock tower, where the bell hangs and the clockwork ticks and whirrs. Tucked behind the great brass gearwheel, wrapped in an old green scarf, is the silver star.",
 "Mr. Budd carries it down as if it were made of eggshell. At the first stroke of midnight Winnie climbs the ladder and sets it on the top of the tree, and the whole lobby cheers. The bell above rings twelve times, exactly as it should.",
 "On the mantelpiece, beside the cocoa, there is a postcard from the seaside that nobody saw arrive. It says: <i>Well done. Merry Christmas. Same time next year? — O.T.</i>",
]
