# Each clue: t=title, x=story text, b=bottom-line rule (printed in italics, self-contained),
# s=solution summary of who is cleared, k='M' (register facts) or 'C' (case columns), f=predicate(p, X)
WARM = ["Honolulu", "Los Angeles", "Miami", "Phoenix", "San Diego", "Tampa"]
def clue(t, x, b, s, k, f): return dict(t=t, x=x, b=b, s=s, k=k, f=f)
def L(xs): return ", ".join(xs[:-1]) + " or " + xs[-1]
LAYOUT = ""

CASES = []

# ---------------------------------------------------------------- CASE 1
CASES.append(dict(num=1, N=40, key="cocoa", cols=[("a", "Topping", ["Marshmallows", "Whipped Cream", "Cinnamon", "Nothing"]),
                                                  ("b", "Seat", ["Fireside", "Window", "Piano"])],
 clues=[
 clue("The Fireside Chairs",
  "Pippa spent the whole of cocoa hour curled up in the big armchair by the fire, reading. She is certain that nobody sitting in the Fireside chairs got up between ten and eleven, because every one of them was listening to Lady Winifred’s story about the time she met a polar bear.",
  "The thief’s Seat is not Fireside.", "Guests seated at the Fireside are cleared", "C", lambda p, X: p["b"] != "Fireside"),
 clue("Early to Bed",
  "The guests who arrived on Friday had signed up for Monday’s dawn snowshoe walk. At a quarter to eleven Gus marched them all into the boot room to wax their snowshoes, and he kept them there, waxing and grumbling, until well after midnight.",
  "The thief did not arrive on Friday.", "Friday arrivals are cleared", "M", lambda p, X: p["arr"] != "Friday"),
 clue("Plain Cocoa",
  "Mrs. Brisket has one firm rule: anyone who takes their cocoa with Nothing on top collects it from the kitchen hatch and never goes near the serving table, where the toppings (and the tin) were kept.",
  "The thief’s Topping is not Nothing.", "Guests who took Nothing on top are cleared", "C", lambda p, X: p["a"] != "Nothing"),
 clue("The Landing",
  "Dot was polishing the banisters on the 3rd-floor landing from eleven until midnight. Nobody went past her, up or down, and the lift had been switched off for the night. The thief carried the tin straight up to their room.",
  "The thief’s room is on the 1st or 2nd floor.", "Guests on floors 3, 4 and 5 are cleared", "M", lambda p, X: p["floor"] <= 2),
 clue("Snow Back Home",
  "The thief was overheard at the serving table saying, “Snow like this? We get it every winter back home.” Of the sixteen home cities that Frostwood guests come from, these are the ones that get heavy snow every winter: Anchorage, Boston, Buffalo, Chicago, Denver, Milwaukee, Minneapolis, Montreal, Quebec City and Toronto.",
  "The thief lives in one of these ten cities: Anchorage, Boston, Buffalo, Chicago, Denver, Milwaukee, Minneapolis, Montreal, Quebec City or Toronto.",
  "Guests from Honolulu, Los Angeles, Miami, Phoenix, San Diego and Tampa are cleared", "M",
  lambda p, X: p["home"] not in WARM),
 clue("The Sticky Shelf",
  "On the shelf where the tin had stood, Mrs. Brisket found a sticky, sugary thumbprint, pink and white and unmistakably marshmallow.",
  "The thief’s Topping is Marshmallows.", "Everyone who did not take Marshmallows is cleared", "C", lambda p, X: p["a"] == "Marshmallows"),
 ]))

# ---------------------------------------------------------------- CASE 2
CASES.append(dict(num=2, N=48, key="hat", cols=[("a", "Team", ["Red", "Blue", "Green", "Gold"]),
                                                ("b", "Snack", ["Chestnuts", "Pretzel", "Toffee Apple", "Soup"])],
 clues=[
 clue("The Judging Line",
  "At half past three, when the hat vanished, the Blue team was standing in a neat row beside their snowman while Mr. Pemberton judged it. He says he never took his eyes off them, “because one of them kept pulling faces at me.”",
  "The thief’s Team is not Blue.", "The Blue team is cleared", "C", lambda p, X: p["a"] != "Blue"),
 clue("Junior Judges",
  "Every Teacher and every Student at the contest had been invited onto the junior judging panel. The panel sat together on the terrace from three o’clock until four, sipping soup and scoring noses.",
  "The thief is not a Teacher and not a Student.", "Teachers and Students are cleared", "M", lambda p, X: p["occ"] not in ("Teacher", "Student")),
 clue("The Welcome-Dinner Joke",
  "The note pinned to the headless snowman read: <i>“Sir Frostington has gone to fetch the soup, like the Colonel.”</i> That joke only makes sense if you heard Colonel Pemberton’s story at Saturday night’s welcome dinner. Guests who arrived on Sunday missed the dinner.",
  "The thief arrived on Friday or Saturday.", "Sunday arrivals are cleared", "M", lambda p, X: p["arr"] in ("Friday", "Saturday")),
 clue("The East Door",
  "Pippa followed a line of footprints from the snowman to the East Door. The East Door opens only onto the East Wing stairs, and Gus saw the thief climb them. On every floor, the East Wing holds the rooms whose last two digits are 11 to 20 (for example, 311 to 320).",
  "The thief’s room number ends in 11 to 20.", "West Wing guests (rooms ending 01 to 10) are cleared", "M", lambda p, X: p["num"] >= 11),
 clue("Snowmen Back Home",
  "The thief had bragged, “Where I come from, snowmen twice this size are built every winter, and the snow lasts until spring.” Of the sixteen home cities that Frostwood guests come from, only these have snow that lasts all winter long: Anchorage, Buffalo, Minneapolis, Montreal, Quebec City and Toronto.",
  "The thief lives in Anchorage, Buffalo, Minneapolis, Montreal, Quebec City or Toronto.",
  "Guests from every other city are cleared", "M",
  lambda p, X: p["home"] in ("Anchorage", "Buffalo", "Minneapolis", "Montreal", "Quebec City", "Toronto")),
 clue("The Dropped Mitten",
  "Beside the snowman lay a mitten with a name tape sewn inside. The ink had run in the wet snow, but the first letter of the surname was clearly from the first part of the alphabet, somewhere from <b>A</b> to <b>L</b>.",
  "The thief’s surname begins with a letter from A to L.", "Surnames M to Z are cleared", "M", lambda p, X: p["last"][0] <= "L"),
 clue("The Toffee Stick",
  "Where the top hat had been, the thief had left a toffee-apple stick, licked perfectly clean. The toffee-apple stall sold its apples only to contestants, one each, and wrote the name of every buyer in the Snack column.",
  "The thief’s Snack is Toffee Apple.", "Everyone whose Snack is not Toffee Apple is cleared", "C", lambda p, X: p["b"] == "Toffee Apple"),
 ]))

# ---------------------------------------------------------------- CASE 3 (the sample case)
CASES.append(dict(num=3, N=60, key="sapphire", cols=[], force_thief="Cyril Nightingale",
 clues=[
 clue("The Back Stairs",
  "Gus the night porter sat at the front desk in the lobby all night long, knitting his very long scarf. He swears that nobody walked through the lobby or used the lift after midnight. The only other way up to the Summit Suite is the narrow back staircase, which begins on the 2nd-floor landing. Guests with rooms on the 1st (ground) floor could not have reached it without passing Gus.",
  "The thief is not staying on the 1st floor.", "Everyone on the 1st floor is cleared", "M", lambda p, X: p["floor"] >= 2),
 clue("The Welcome Dinner",
  "Lady Winifred tells people where she keeps the necklace at night only once a year: at the welcome dinner, which was held on Saturday evening. She announced it rather loudly over the soup. Guests who arrived on Sunday missed the dinner entirely and had no idea where to look.",
  "The thief arrived on Friday or Saturday.", "Sunday arrivals are cleared", "M", lambda p, X: p["arr"] in ("Friday", "Saturday")),
 clue("The Midnight Hiccups",
  "At half past one, a guest in the library came down with a spectacular case of the hiccups. Every Doctor and every Nurse staying at the lodge hurried to the library and stayed there until well after three, arguing cheerfully about the best cure.",
  "The thief is not a Doctor and not a Nurse.", "Doctors and Nurses are cleared", "M", lambda p, X: p["occ"] not in ("Doctor", "Nurse")),
 clue("Borrowed Boots",
  "On Sunday evening, a guest came to the front desk to borrow a pair of snow boots, admitting that they had “never seen real snow before in my whole life.” Dot found those very boots, still damp, outside the Summit Suite. Of the sixteen home cities that Frostwood guests come from, the ones where it practically never snows are Honolulu, Los Angeles, Miami, Phoenix, San Diego and Tampa.",
  "The thief lives in Honolulu, Los Angeles, Miami, Phoenix, San Diego or Tampa.",
  "Guests from the ten snowy cities are cleared", "M", lambda p, X: p["home"] in WARM),
 clue("The Clicking Door",
  "Dot the chambermaid was up early warming the towels. Just after two, she heard a door on the mountain side of a corridor click softly shut. On every floor of the lodge, the rooms on the mountain side have even numbers.",
  "The thief’s room number is even.", "Odd-numbered rooms are cleared", "M", lambda p, X: p["room"] % 2 == 0),
 clue("The Monogram",
  "Caught on a nail at the top of the back stairs was a scrap of a handkerchief, embroidered with the tail end of a letter. It was the initial of the thief’s surname, and it could only have been a letter from the second half of the alphabet: <b>N</b> to <b>Z</b>.",
  "The thief’s surname begins with a letter from N to Z.", "Surnames A to M are cleared", "M", lambda p, X: p["last"][0] >= "N"),
 clue("Out of Breath",
  "The last clue comes from Lady Winifred herself. She half-woke in the night and heard someone outside her door, panting and puffing “as though they had just climbed a mountain.” The Summit Suite sits just a few steps above the 5th floor, so a guest from the 5th floor would not have been out of breath at all.",
  "The thief is not staying on the 5th floor.", "The 5th-floor guests are cleared", "M", lambda p, X: p["floor"] != 5),
 clue("Nobody to Vouch",
  "Everyone who shared a room was woken by the wind at about two o’clock, the time of the theft, and each can vouch that their roommates were right there, grumbling about the draught. (Guests who share a room have the same room number in the register.)",
  "The thief is staying in a room alone.", "Everyone sharing a room is cleared", "M", lambda p, X: X.party(p) == 1),
 ]))

# ---------------------------------------------------------------- CASE 4
CASES.append(dict(num=4, N=64, key="sponge", cols=[("a", "Entry", ["Sponge", "Tart", "Scones", "Shortbread", "Pie"]),
                                                   ("b", "Station", ["A", "B", "C", "D"])],
 clues=[
 clue("The West Pantry",
  "The salt and sugar were swapped in the west pantry. Contestants at Stations A and B fetched their ingredients from the east pantry at the other end of the hall, and Mrs. Brisket, who stood guard there, says not one of them wandered.",
  "The thief’s Station is C or D.", "Stations A and B are cleared", "C", lambda p, X: p["b"] in ("C", "D")),
 clue("The Judges’ Table",
  "Every Chef and every Baker staying at the lodge had been asked to help judge, and they sat together on the stage for the whole contest, where everybody could see them.",
  "The thief is not a Chef and not a Baker.", "Chefs and Bakers are cleared", "M", lambda p, X: p["occ"] not in ("Chef", "Baker")),
 clue("In the Oven",
  "The swap happened at twenty past two. At exactly that moment, everyone baking Scones or Pie was kneeling in front of the ovens, watching their entries rise, because the ovens at Frostwood are famous for their tempers.",
  "The thief’s Entry is not Scones and not Pie.", "Scone and Pie bakers are cleared", "C", lambda p, X: p["a"] not in ("Scones", "Pie")),
 clue("The Lift Indicator",
  "Just after the swap, the thief slipped out and took the lift upstairs to hide the sugar. Gus watched the brass arrow above the lift doors: it stopped at the 3rd floor and at the 4th floor, and nowhere else, before coming back down empty.",
  "The thief’s room is on the 3rd or 4th floor.", "Guests on floors 1, 2 and 5 are cleared", "M", lambda p, X: p["floor"] in (3, 4)),
 clue("A Whispered Word",
  "Pippa, hiding behind a flour sack, heard the thief mutter, “Wait until I tell my roommate about this.” (Guests who share a room have the same room number in the register.)",
  "The thief shares a room with at least one other guest.", "Guests staying alone are cleared", "M", lambda p, X: X.party(p) >= 2),
 clue("The Apron",
  "An apron was left crumpled in the west pantry, embroidered with a single initial: the first letter of the thief’s first name. The embroidery was worn, but it was certainly a letter from <b>A</b> to <b>M</b>.",
  "The thief’s first name begins with a letter from A to M.", "First names N to Z are cleared", "M", lambda p, X: p["first"][0] <= "M"),
 clue("Sea Salt",
  "Tasting the ruined sponge, the thief was heard to say, “That’s nothing like the sea salt we get at home, right by the ocean.” Of the sixteen home cities that Frostwood guests come from, these are the ones beside the sea: Anchorage, Boston, Honolulu, Los Angeles, Miami, San Diego and Tampa.",
  "The thief lives in Anchorage, Boston, Honolulu, Los Angeles, Miami, San Diego or Tampa.",
  "Guests from inland or lakeside cities are cleared", "M",
  lambda p, X: p["home"] in ("Anchorage", "Boston", "Honolulu", "Los Angeles", "Miami", "San Diego", "Tampa")),
 clue("Cinnamon Sugar",
  "The lid of the sugar jar was dusted with cinnamon sugar. Only two recipes in the whole contest used cinnamon sugar: the Tart and the Shortbread.",
  "The thief’s Entry is Tart or Shortbread.", "Sponge bakers are cleared", "C", lambda p, X: p["a"] in ("Tart", "Shortbread")),
 ]))

# ---------------------------------------------------------------- CASE 5
CASES.append(dict(num=5, N=72, key="book", cols=[("a", "Borrowed", ["Mystery", "Poetry", "Travel", "Cookery", "Science"]),
                                                 ("b", "Visited", ["Morning", "Afternoon", "Evening"])],
 clues=[
 clue("The Poetry Circle",
  "The library’s cuckoo clock was nudged and stopped at 11:15 p.m. as the book was lifted from its case. At that moment every guest who had borrowed a Poetry book was in the conservatory at the Poetry Circle, reading aloud by candle-lantern.",
  "The thief’s Borrowed book is not Poetry.", "Poetry borrowers are cleared", "C", lambda p, X: p["a"] != "Poetry"),
 clue("The Late Jam Session",
  "Also at 11:15 p.m., every Violinist, Painter and Photographer at the lodge was in the Music Room for an impromptu jam session. The Photographers were taking pictures; the Painters were mostly tapping on biscuit tins.",
  "The thief is not a Violinist, a Painter or a Photographer.", "Violinists, Painters and Photographers are cleared", "M",
  lambda p, X: p["occ"] not in ("Violinist", "Painter", "Photographer")),
 clue("The West Stairs",
  "The library sits in the West Wing, and Dot found a bookmark from the book on the West Wing stairs. Gus has confirmed the thief used them to go straight to their room. The West Wing holds the rooms whose last two digits are 01 to 10 on every floor (for example, 401 to 410).",
  "The thief’s room number ends in 01 to 10.", "East Wing guests (rooms ending 11 to 20) are cleared", "M", lambda p, X: p["num"] <= 10),
 clue("Two Teacups",
  "The next morning, Dot collected a tray from outside the thief’s door. On it were exactly two teacups, two saucers, and the lodge’s rule is one cup per guest in the room. (Guests who share a room have the same room number in the register.)",
  "The thief’s room holds exactly two guests.", "Guests staying alone or three to a room are cleared", "M", lambda p, X: X.party(p) == 2),
 clue("A Library Card",
  "The thief used a library card to prop open the glass case, and left it behind by mistake. Friday arrivals were given blue library cards; everyone else got green ones. The card left behind was green.",
  "The thief did not arrive on Friday.", "Friday arrivals are cleared", "M", lambda p, X: p["arr"] != "Friday"),
 clue("The Author’s Tour",
  "When the book first came out, its author toured six cities to sign copies. The thief told Pippa, “I met the author when the tour came to my home town.” The six tour cities were Boston, Buffalo, Chicago, Montreal, Quebec City and Toronto.",
  "The thief lives in Boston, Buffalo, Chicago, Montreal, Quebec City or Toronto.",
  "Guests from the other ten cities are cleared", "M",
  lambda p, X: p["home"] in ("Boston", "Buffalo", "Chicago", "Montreal", "Quebec City", "Toronto")),
 clue("After Lunch",
  "The book was only moved into its glass case at lunchtime on Tuesday. Guests who visited the library in the Morning saw it on the old oak shelf, and would have gone looking there.",
  "The thief Visited in the Afternoon or the Evening.", "Morning visitors are cleared", "C", lambda p, X: p["b"] in ("Afternoon", "Evening")),
 clue("The Pressed Flower",
  "Tucked inside the glass case was a pressed sprig of edelweiss that had fallen out of the thief’s own library book. Miss Lettice, the librarian, knows her shelves: only the Travel and Mystery books have pressed flowers for bookmarks.",
  "The thief’s Borrowed book is Travel or Mystery.", "Cookery and Science borrowers are cleared", "C", lambda p, X: p["a"] in ("Travel", "Mystery")),
 clue("The Signature",
  "In the visitors’ book, the thief’s surname had been hastily scribbled out, but Pippa counted the humps and loops with a magnifying glass. The surname had more than six letters.",
  "The thief’s surname has seven or more letters.", "Surnames of six letters or fewer are cleared", "M", lambda p, X: len(p["last"]) > 6),
 ]))

# ---------------------------------------------------------------- CASE 6
CASES.append(dict(num=6, N=80, key="laces", cols=[("a", "Heat", ["1", "2", "3", "4"]),
                                                  ("b", "Scarf", ["Red", "Blue", "Green", "Striped"])],
 clues=[
 clue("Warming Up",
  "At three o’clock, when the laces vanished, the skaters in Heat 1 were already out on the ice warming up, going round and round under the eye of the race marshal.",
  "The thief’s Heat is not 1.", "Heat 1 skaters are cleared", "C", lambda p, X: p["a"] != "1"),
 clue("The First-Aid Tent",
  "Every Doctor, Nurse and Dentist at the lodge was running the first-aid tent beside the lake, which mostly meant handing out blankets and hot cocoa. They stayed there together all afternoon.",
  "The thief is not a Doctor, a Nurse or a Dentist.", "Doctors, Nurses and Dentists are cleared", "M",
  lambda p, X: p["occ"] not in ("Doctor", "Nurse", "Dentist")),
 clue("The Lake View",
  "The skate shed can only be seen from the lake side of the lodge. The thief waited at their bedroom window until the coast was clear. On every floor, the rooms on the lake side have odd numbers.",
  "The thief’s room number is odd.", "Even-numbered rooms are cleared", "M", lambda p, X: p["room"] % 2 == 1),
 clue("Where’s the Shed?",
  "At lunchtime, the thief asked Gus where the skate shed was. Anyone who arrived on Friday or Saturday had been shown the shed on Saturday’s lakeside walk, and would not have needed to ask.",
  "The thief arrived on Sunday.", "Friday and Saturday arrivals are cleared", "M", lambda p, X: p["arr"] == "Sunday"),
 clue("Frozen Ponds",
  "The knot was tied in the style of a pond-hockey net, and the thief admitted to Pippa, “We skate on the frozen lakes back home every winter.” Of the sixteen home cities that Frostwood guests come from, these have frozen lakes or ponds for skating every winter: Anchorage, Buffalo, Chicago, Milwaukee, Minneapolis, Montreal and Toronto.",
  "The thief lives in Anchorage, Buffalo, Chicago, Milwaukee, Minneapolis, Montreal or Toronto.",
  "Guests from the other nine cities are cleared", "M",
  lambda p, X: p["home"] in ("Anchorage", "Buffalo", "Chicago", "Milwaukee", "Minneapolis", "Montreal", "Toronto")),
 clue("The Hot-Water Bottles",
  "Between a quarter to three and a quarter past, Dot delivered hot-water bottles to every guest on the 4th and 5th floors, and every one of them answered the door in person, wrapped in a blanket.",
  "The thief’s room is on the 1st, 2nd or 3rd floor.", "Guests on the 4th and 5th floors are cleared", "M", lambda p, X: p["floor"] <= 3),
 clue("Green Fluff",
  "Picked out of the knot of laces with tweezers: several strands of green wool. Only Green scarves and Striped scarves (which are green and white) have green wool in them.",
  "The thief’s Scarf is Green or Striped.", "Red and Blue scarves are cleared", "C", lambda p, X: p["b"] in ("Green", "Striped")),
 clue("The Sign-Up Sheet",
  "The thief crossed their own name off the sign-up sheet in a fit of guilt, but the sheet is in alphabetical order, and the crossed-out line falls in the section for surnames beginning <b>A</b> to <b>M</b>.",
  "The thief’s surname begins with a letter from A to M.", "Surnames N to Z are cleared", "M", lambda p, X: p["last"][0] <= "M"),
 clue("Say Cheese",
  "From ten to three until ten past, the skaters in Heat 2 were lined up by the boathouse having their team photograph taken. It took twenty minutes because somebody kept blinking.",
  "The thief’s Heat is not 2.", "Heat 2 skaters are cleared", "C", lambda p, X: p["a"] != "2"),
 ]))

# ---------------------------------------------------------------- CASE 7
CASES.append(dict(num=7, N=90, key="feast", cols=[("a", "Pyjamas", ["Plaid", "Spotted", "Striped", "Plain"]),
                                                  ("b", "Slippers", ["Bunny", "Moccasin", "Woolly", "None"])],
 clues=[
 clue("The Crumb Trail",
  "A trail of pastry crumbs led from the cold larder to the West Wing stairs, and Dot followed it all the way up to the thief’s floor. The West Wing holds the rooms whose last two digits are 01 to 10 (for example, 201 to 210).",
  "The thief’s room number ends in 01 to 10.", "East Wing guests (rooms ending 11 to 20) are cleared", "M", lambda p, X: p["num"] <= 10),
 clue("Gus’s Glimpse",
  "At one in the morning Gus caught a glimpse of the thief’s back disappearing round a corner. He couldn’t see a face, but the pyjamas were definitely lined: either Striped or Plaid. (Spotted and Plain pyjamas have no lines.)",
  "The thief’s Pyjamas are Striped or Plaid.", "Spotted and Plain pyjamas are cleared", "C", lambda p, X: p["a"] in ("Striped", "Plaid")),
 clue("The Cold Stone Floor",
  "The larder floor is solid stone and freezing cold. Mrs. Brisket found no bare footprints, only the soft scuffs of slippers.",
  "The thief’s Slippers are not None.", "Guests with no slippers are cleared", "C", lambda p, X: p["b"] != "None"),
 clue("The Midnight Movie",
  "Every Student at the lodge was at the midnight movie in the games room, chaperoned by every Teacher at the lodge. The film was three hours long and very loud, and nobody left before two.",
  "The thief is not a Student and not a Teacher.", "Students and Teachers are cleared", "M",
  lambda p, X: p["occ"] not in ("Student", "Teacher")),
 clue("Not the Ground Floor",
  "Gus’s desk looks straight down the 1st-floor corridor. He is sure no 1st-floor door opened all night.",
  "The thief is not staying on the 1st floor.", "1st-floor guests are cleared", "M", lambda p, X: p["floor"] != 1),
 clue("The Postcard",
  "Among the crumbs was a half-written postcard: “Dear Mum, the pastries in the United States are…” Of the sixteen home cities that Frostwood guests come from, the Canadian ones are Montreal, Quebec City and Toronto; all the others are in the United States.",
  "The thief does not live in Montreal, Quebec City or Toronto.", "Guests from Montreal, Quebec City and Toronto are cleared", "M",
  lambda p, X: p["home"] not in ("Montreal", "Quebec City", "Toronto")),
 clue("The Squeaky Board",
  "The third board inside the larder door squeaks loudly under anything hard-soled, and Moccasins are hard-soled. It did not squeak all night: Mrs. Brisket’s cat sleeps beside it and would have woken up. Only Woolly and Bunny slippers are soft enough to cross it silently.",
  "The thief’s Slippers are Woolly or Bunny.", "Moccasin wearers are cleared", "C", lambda p, X: p["b"] in ("Woolly", "Bunny")),
 clue("Plaid or Bunny",
  "The cat’s whiskers had caught one tuft of fluff, and Mrs. Brisket, who knows her fabrics, says it came either from Plaid pyjamas or from Bunny slippers. Gus, who saw the thief’s back, is equally sure the thief was not wearing both at once: “Plaid with bunnies? I’d have remembered that.”",
  "Exactly one is true: the thief’s Pyjamas are Plaid, or the thief’s Slippers are Bunny. (Not both, not neither.)",
  "Guests with both, or with neither, are cleared", "C", lambda p, X: (p["a"] == "Plaid") != (p["b"] == "Bunny")),
 clue("The Door Number",
  "The last crumb lay outside a door on the mountain side of the corridor. On every floor, the rooms on the mountain side have even numbers.",
  "The thief’s room number is even.", "Odd-numbered rooms are cleared", "M", lambda p, X: p["room"] % 2 == 0),
 clue("The Borrowed Key",
  "The larder was locked, and the thief opened it with a key. On Sunday, Mrs. Brisket gave a spare larder key to every Chef and every Baker in the lodge, for the Bake-Off. The thief must have borrowed one from a roommate. (Guests who share a room have the same room number in the register.)",
  "Someone else in the thief’s room is a Chef or a Baker.", "Guests with no Chef or Baker among their roommates are cleared", "M",
  lambda p, X: any(q["occ"] in ("Chef", "Baker") for q in X.mates(p))),
 ]))

# ---------------------------------------------------------------- CASE 8
EASTERN = ["Boston", "Buffalo", "Miami", "Montreal", "Quebec City", "Tampa", "Toronto"]
CASES.append(dict(num=8, N=100, key="globe", cols=[("a", "At 3 p.m.", ["Sauna", "Library", "Skating", "Sledding", "Snowshoeing", "Cards"]),
                                                   ("b", "Coat", ["Parka", "Duffle", "Cape", "Fleece"])],
 clues=[
 clue("Snow on the Carpet",
  "Under the lobby mantel where the snow globe had stood, Pippa found a little puddle of melted snow. The thief had come in from outdoors. The outdoor activities at 3 p.m. were Skating, Sledding and Snowshoeing.",
  "The thief was Skating, Sledding or Snowshoeing at 3 p.m.", "Sauna, Library and Cards guests are cleared", "C",
  lambda p, X: p["a"] in ("Skating", "Sledding", "Snowshoeing")),
 clue("The Cloakroom",
  "Capes are not allowed on the sledding hill or the lake, so every Cape was hung up in the cloakroom at two o’clock, and Gus locked the door until five. No guest wearing a Cape could have been outdoors.",
  "The thief’s Coat is not Cape.", "Cape wearers are cleared", "C", lambda p, X: p["b"] != "Cape"),
 clue("The Grand Staircase",
  "The globe is heavy, so the thief carried it up the Grand Staircase rather than risk the creaky lift. Dot was on the 2nd-floor landing and saw somebody hurry past her with a bulging coat, heading further up.",
  "The thief’s room is on the 3rd, 4th or 5th floor.", "Guests on floors 1 and 2 are cleared", "M", lambda p, X: p["floor"] >= 3),
 clue("The Interview",
  "From three until four, every Photographer, Journalist and Novelist at the lodge was up in the Summit Suite interviewing Lady Winifred for a magazine article about her polar bear.",
  "The thief is not a Photographer, a Journalist or a Novelist.", "Photographers, Journalists and Novelists are cleared", "M",
  lambda p, X: p["occ"] not in ("Photographer", "Journalist", "Novelist")),
 clue("Across the Hall",
  "When the thief’s door clicked shut, the door directly across the hall opened, and a guest peeped out and called, “Did you hear that?” (Across the hall means the facing room: every odd-numbered room faces the next even number, so 305 faces 306 and 419 faces 420.)",
  "The room directly across the hall from the thief’s room has at least one guest listed on this register.",
  "Guests whose facing room has nobody on the register are cleared", "M", lambda p, X: len(X.across(p)) > 0),
 clue("The Dining Room",
  "Until Saturday lunchtime, the snow globe lived in the dining room. Friday arrivals had only ever seen it there, and they all still think it’s there; Pippa asked every one of them.",
  "The thief did not arrive on Friday.", "Friday arrivals are cleared", "M", lambda p, X: p["arr"] != "Friday"),
 clue("Eastern Time",
  "The thief’s wristwatch left a print in the dust on the mantel, and Pippa noticed the thief checking it: it was still set to Eastern Time, the time back home. Of the sixteen home cities that Frostwood guests come from, these are on Eastern Time: Boston, Buffalo, Miami, Montreal, Quebec City, Tampa and Toronto.",
  "The thief lives in Boston, Buffalo, Miami, Montreal, Quebec City, Tampa or Toronto.",
  "Guests from the other nine cities are cleared", "M", lambda p, X: p["home"] in EASTERN),
 clue("The Toggle",
  "On the lobby rug lay a small wooden toggle. Of the four kinds of coat in the register, only a Duffle coat is fastened with toggles.",
  "The thief’s Coat is Duffle.", "Parka and Fleece wearers are cleared", "C", lambda p, X: p["b"] == "Duffle"),
 clue("The Creaking Ceiling",
  "That evening, the thief complained to Gus about footsteps creaking overhead. Rooms stack neatly: the room directly above Room 305 is Room 405. (Rooms on the 5th floor have only the attic above them, which is empty.)",
  "The room directly above the thief’s room has at least one guest listed on this register.",
  "Guests with nobody on the register directly above are cleared", "M", lambda p, X: len(X.above(p)) > 0),
 clue("The Initial",
  "The snow globe was found at last, wrapped in a pillowcase monogrammed with the initial of the surname it had been embroidered for: a letter from <b>N</b> to <b>Z</b>. The thief had brought it from home.",
  "The thief’s surname begins with a letter from N to Z.", "Surnames A to M are cleared", "M", lambda p, X: p["last"][0] >= "N"),
 ]))

# ---------------------------------------------------------------- CASE 9
CASES.append(dict(num=9, N=110, key="ghost", cols=[("a", "Bedtime", ["9 p.m.", "10 p.m.", "11 p.m.", "Midnight"]),
                                                   ("b", "Nightcap", ["Chamomile", "Peppermint", "Earl Grey", "Cocoa"])],
 clues=[
 clue("Wide Awake",
  "The “ghost” appeared at one in the morning. Dot keeps a list of every guest’s usual bedtime for the evening turn-down service, and she is certain the early sleepers were snoring by midnight: she heard them. Only guests with a Bedtime of 11 p.m. or Midnight were still up and about.",
  "The thief’s Bedtime is 11 p.m. or Midnight.", "Guests with a 9 p.m. or 10 p.m. Bedtime are cleared", "C",
  lambda p, X: p["a"] in ("11 p.m.", "Midnight")),
 clue("The East Corridor",
  "The ghost swept off the East stairs and into the East Wing corridor, and the East Wing door locks behind anyone who goes through it without a room key for that wing. The East Wing holds the rooms whose last two digits are 11 to 20 on every floor (for example, 511 to 520).",
  "The thief’s room number ends in 11 to 20.", "West Wing guests (rooms ending 01 to 10) are cleared", "M", lambda p, X: p["num"] >= 11),
 clue("Up the Stairs",
  "Mr. Grayle, who met the ghost on the 2nd-floor landing, says it fled <i>upwards</i> “with a most unghostly clatter.” It went to its own room from there.",
  "The thief’s room is on the 3rd, 4th or 5th floor.", "Guests on floors 1 and 2 are cleared", "M", lambda p, X: p["floor"] >= 3),
 clue("Dot’s Rounds",
  "Chamomile tea at Frostwood is brewed strong enough to send a moose to sleep. Everyone whose Nightcap was Chamomile was fast asleep before half past twelve; Dot checked on each of them.",
  "The thief’s Nightcap is not Chamomile.", "Chamomile drinkers are cleared", "C", lambda p, X: p["b"] != "Chamomile"),
 clue("The Laundry Tag",
  "The ghost’s sheet was found stuffed down the laundry chute. Its laundry tag shows it came from a room made up with two or more beds, and only rooms shared by two or more guests are made up that way. (Guests who share a room have the same room number in the register.)",
  "The thief shares a room with at least one other guest.", "Guests staying alone are cleared", "M", lambda p, X: X.party(p) >= 2),
 clue("The Card Tower",
  "Every Pilot, Engineer and Architect at the lodge spent the whole night in the games room, building a tower of playing cards eleven storeys high. Nobody dared leave in case it fell down.",
  "The thief is not a Pilot, an Engineer or an Architect.", "Pilots, Engineers and Architects are cleared", "M",
  lambda p, X: p["occ"] not in ("Pilot", "Engineer", "Architect")),
 clue("The Midnight Snack",
  "Every Student in the lodge was awake at one o’clock, sharing a secret midnight snack in their own room, and each one says their roommates never left. So the ghost does not share a room with a Student. (Guests who share a room have the same room number in the register.)",
  "None of the thief’s roommates is a Student.", "Guests who share a room with a Student are cleared", "M",
  lambda p, X: all(q["occ"] != "Student" for q in X.mates(p))),
 clue("Thumping",
  "At ten past one, a guest rang the front desk to complain about “thumping and wailing” from the room directly above. Rooms stack neatly: the room directly above Room 314 is Room 414. The complaint came from the room directly below the thief’s, and that caller is on this register. (1st-floor rooms have only the cellar below them.)",
  "The room directly below the thief’s room has at least one guest listed on this register.",
  "Guests with nobody on the register directly below are cleared", "M", lambda p, X: len(X.below(p)) > 0),
 clue("The Grey Lady",
  "The ghost called itself “the Grey Lady of Frostwood.” That legend is told only twice a week: at the Saturday welcome dinner (so every guest who arrived on Friday or Saturday heard it), and at the late-night story hour, which only guests with a Bedtime of Midnight attend.",
  "At least one is true: the thief arrived on Friday or Saturday, or the thief’s Bedtime is Midnight.",
  "Sunday arrivals whose Bedtime is not Midnight are cleared", "C", lambda p, X: p["arr"] in ("Friday", "Saturday") or p["a"] == "Midnight"),
 clue("The Empty Mug",
  "On the stairs where the ghost vanished stood an empty mug with a little ring in the bottom that smelled of chocolate and mint. Only Cocoa and Peppermint nightcaps are served in mugs; Earl Grey comes in a china cup.",
  "The thief’s Nightcap is Cocoa or Peppermint.", "Earl Grey drinkers are cleared", "C", lambda p, X: p["b"] in ("Cocoa", "Peppermint")),
 clue("The Subway Token",
  "Tangled in the sheet was a keyring with a subway token on it. The thief said, “I always keep one for the ride home.” Of the sixteen home cities that Frostwood guests come from, these have an underground subway line: Boston, Buffalo, Chicago, Los Angeles, Montreal and Toronto.",
  "The thief lives in Boston, Buffalo, Chicago, Los Angeles, Montreal or Toronto.",
  "Guests from the other ten cities are cleared", "M",
  lambda p, X: p["home"] in ("Boston", "Buffalo", "Chicago", "Los Angeles", "Montreal", "Toronto")),
 ]))

# ---------------------------------------------------------------- CASE 10
CANADA = ("Montreal", "Quebec City", "Toronto")
CASES.append(dict(num=10, N=125, key="quartet", cols=[("a", "Act", ["Singing", "Magic", "Juggling", "Poetry", "Piano", "Audience"]),
                                                      ("b", "Rehearsal", ["4 p.m.", "5 p.m.", "6 p.m.", "7 p.m."])],
 clues=[
 clue("Ballroom Rehearsal",
  "The bows and music vanished from the Music Room between a quarter to six and a quarter past. Everyone with a 6 p.m. Rehearsal was in the ballroom at that time, rehearsing under Pippa’s stern eye.",
  "The thief’s Rehearsal is not 6 p.m.", "6 p.m. rehearsers are cleared", "C", lambda p, X: p["b"] != "6 p.m."),
 clue("Backstage Pass",
  "The Music Room can only be reached through the backstage corridor, and on Talent Evening only performers are allowed backstage. Guests whose Act is Audience were not performing and were stopped at the curtain.",
  "The thief’s Act is not Audience.", "Audience members are cleared", "C", lambda p, X: p["a"] != "Audience"),
 clue("The Dressing Room",
  "The Poetry and Magic performers shared a dressing room with the quartet’s cellist, who was mending a string all evening and says none of them left the room before the show.",
  "The thief’s Act is not Poetry and not Magic.", "Poets and Magicians are cleared", "C", lambda p, X: p["a"] not in ("Poetry", "Magic")),
 clue("The Laundry Chute",
  "The quartet’s sheet music was found at the bottom of the laundry chute. The chute has hatches only on the 2nd and 4th floors, and the thief used the one on their own floor.",
  "The thief’s room is on the 2nd or 4th floor.", "Guests on floors 1, 3 and 5 are cleared", "M", lambda p, X: p["floor"] in (2, 4)),
 clue("Fluttering Pages",
  "At ten past six, one loose page of music was seen fluttering past a window on the mountain side of the lodge, dropped by the thief from their own room. On every floor, the rooms on the mountain side have even numbers.",
  "The thief’s room number is even.", "Odd-numbered rooms are cleared", "M", lambda p, X: p["room"] % 2 == 0),
 clue("Quiet Above",
  "The thief spent an hour practising scales on a borrowed bow, loudly and badly, and nobody complained. Rooms stack neatly: the room directly above Room 214 is Room 314. Every guest on this register was in their room at that hour, so the room above the thief’s must have had no one from this register in it. (5th-floor rooms have only the empty attic above them.)",
  "No guest on this register is staying in the room directly above the thief’s room.",
  "Guests with a registered guest directly above them are cleared", "M", lambda p, X: len(X.above(p)) == 0),
 clue("Setting the Stage",
  "Every Violinist, Tailor and Photographer at the lodge spent the afternoon and evening in the Great Hall, building the stage, stitching the curtains and setting up the lights.",
  "The thief is not a Violinist, a Tailor or a Photographer.", "Violinists, Tailors and Photographers are cleared", "M",
  lambda p, X: p["occ"] not in ("Violinist", "Tailor", "Photographer")),
 clue("The Quartet’s Dinner",
  "The thief knew exactly which case held the bows. The quartet had shown off their bows, case and all, only once: when they played at the Saturday welcome dinner. Sunday arrivals missed it.",
  "The thief arrived on Friday or Saturday.", "Sunday arrivals are cleared", "M", lambda p, X: p["arr"] in ("Friday", "Saturday")),
 clue("Two Possibilities",
  "Pippa found a rehearsal timetable in the Music Room with a scribbled note in French. Either the thief rehearsed at 4 p.m. (the only slot that would have given time to scout the Music Room), or the thief lives in one of the Canadian home cities (Montreal, Quebec City or Toronto), where French is taught in every school, or both.",
  "At least one is true: the thief’s Rehearsal is 4 p.m., or the thief lives in Montreal, Quebec City or Toronto.",
  "Guests with neither are cleared", "C", lambda p, X: p["b"] == "4 p.m." or p["home"] in CANADA),
 clue("A Room of One’s Own",
  "Nobody noticed the thief come and go with a violin case full of bows. Every guest who shares a room says their roommates were in all evening, and none of them had a violin case. (Guests who share a room have the same room number in the register.)",
  "The thief is staying in a room alone.", "Everyone sharing a room is cleared", "M", lambda p, X: X.party(p) == 1),
 clue("The Name Card",
  "The thief’s name card from the talent show running order was found crumpled in the chute. Only the first letter of the surname survived: a letter from <b>A</b> to <b>M</b>.",
  "The thief’s surname begins with a letter from A to M.", "Surnames N to Z are cleared", "M", lambda p, X: p["last"][0] <= "M"),
 clue("Rosin on the Cuff",
  "The thief’s cuffs were dusted with rosin, the sticky powder rubbed on bows. Mrs. Brisket noticed it at supper, and the only acts that had been practising with their hands near the rosin were Singing (the singers were holding the sheet music) and Piano.",
  "The thief’s Act is Singing or Piano.", "Jugglers are cleared", "C", lambda p, X: p["a"] in ("Singing", "Piano")),
 ]))

# ---------------------------------------------------------------- CASE 11
CASES.append(dict(num=11, N=138, key="key", cols=[("a", "Breakfast", ["Porridge", "Pancakes", "Eggs", "Fruit", "Kippers", "Skipped"]),
                                                  ("b", "Table", ["1", "2", "3", "4", "5", "6", "7", "8"])],
 clues=[
 clue("Through the Dining Room",
  "Mr. Pemberton’s office can only be reached through the dining room, and Gus was watching the other door. Guests who Skipped breakfast never came into the dining room.",
  "The thief’s Breakfast is not Skipped.", "Guests who Skipped breakfast are cleared", "C", lambda p, X: p["a"] != "Skipped"),
 clue("Syrup on the Hook",
  "The key hook was sticky with golden syrup. At Frostwood, golden syrup is served only with Porridge and Pancakes.",
  "The thief’s Breakfast is Porridge or Pancakes.", "Eggs, Fruit and Kippers eaters are cleared", "C", lambda p, X: p["a"] in ("Porridge", "Pancakes")),
 clue("The Breakfast Ticket",
  "Every breakfast ticket has the guest’s table number and room number printed on it. Half of the thief’s ticket was found under the hook, and Pippa worked out one thing from it: the table number was greater than the floor number (the floor is the first digit of the room number).",
  "The thief’s Table number is greater than the thief’s floor number.", "Guests whose Table is equal to or smaller than their floor are cleared", "C",
  lambda p, X: int(p["b"]) > p["floor"]),
 clue("The Chess Tournament",
  "Every Accountant and every Lawyer in the lodge was playing in the Saturday chess tournament in the games room, which began at seven sharp and did not break for breakfast.",
  "The thief is not an Accountant and not a Lawyer.", "Accountants and Lawyers are cleared", "M", lambda p, X: p["occ"] not in ("Accountant", "Lawyer")),
 clue("Breakfast in Bed",
  "On Saturdays it is a Frostwood tradition that every guest on the 3rd floor is served breakfast in bed. Dot carried up every tray herself, and every one of those guests was still in bed when she collected the trays at nine.",
  "The thief is not staying on the 3rd floor.", "3rd-floor guests are cleared", "M", lambda p, X: p["floor"] != 3),
 clue("The Neighbour’s Knock",
  "The thief was seen slipping the key into the room next door to their own, to hide it. Next door means the room two numbers higher or lower on the same floor and the same side of the corridor (Room 407 is next door to 405 and 409; Room 401 has only 403 beside it; Room 420 has only 418).",
  "At least one room next door to the thief’s room has a guest listed on this register.",
  "Guests with no registered guest next door are cleared", "M", lambda p, X: len(X.nextdoor(p)) > 0),
 clue("Nobody Across the Hall",
  "Nobody saw the thief come or go, not even the guest across the hall. Across the hall means the facing room: every odd-numbered room faces the next even number (Room 305 faces 306; Room 419 faces 420). The room across the hall from the thief’s has no one from this register in it.",
  "No guest on this register is staying in the room directly across the hall from the thief’s room.",
  "Guests with a registered guest across the hall are cleared", "M", lambda p, X: len(X.across(p)) == 0),
 clue("Gentle Winters",
  "The thief was heard grumbling that the snow “never lets up,” and that winters back home are gentle and green. Of the sixteen home cities that Frostwood guests come from, these have gentle, snowless winters: Honolulu, Los Angeles, Miami, Phoenix, San Diego and Tampa.",
  "The thief lives in Honolulu, Los Angeles, Miami, Phoenix, San Diego or Tampa.", "Guests from the ten snowy cities are cleared", "M",
  lambda p, X: p["home"] in WARM),
 clue("Company",
  "At seven o’clock Dot saw the thief slip out of their room, whispering “Go back to sleep, I’ll bring you some breakfast,” to somebody still inside. (Guests who share a room have the same room number in the register.)",
  "The thief shares a room with at least one other guest.", "Guests staying alone are cleared", "M", lambda p, X: X.party(p) >= 2),
 clue("A Family Affair",
  "The sleepy voice inside answered, “Thank you, my darling grandchild.” So the thief is sharing a room with a relative, and in this register, relatives travelling together always share a surname.",
  "At least one other guest in the thief’s room has the same surname as the thief.",
  "Guests with no roommate of the same surname are cleared", "M", lambda p, X: any(q["last"] == p["last"] for q in X.mates(p))),
 clue("Even Stevens",
  "On Saturdays Mrs. Brisket serves the even-numbered tables first. The thief finished early and was at the key hook while the odd-numbered tables were still waiting for their toast.",
  "The thief’s Table number is even.", "Guests at odd-numbered tables are cleared", "C", lambda p, X: int(p["b"]) % 2 == 0),
 clue("The Pancake Lesson",
  "Every guest at Table 4 spent breakfast in the kitchen, where Mrs. Brisket was teaching them to flip pancakes. The ceiling still has evidence.",
  "The thief’s Table is not 4.", "Table 4 guests are cleared", "C", lambda p, X: p["b"] != "4"),
 clue("The Name Tag",
  "Pippa found the thief’s paper name tag in the dining room fireplace, half burnt. The first name and surname were both still readable except for the middle letters, and she counted: the first name was shorter than the surname.",
  "The thief’s first name has fewer letters than the thief’s surname.", "Guests whose first name is as long as or longer than their surname are cleared", "M",
  lambda p, X: len(p["first"]) < len(p["last"])),
 ]))

# ---------------------------------------------------------------- CASE 12
CASES.append(dict(num=12, N=152, key="portrait", cols=[("a", "At 11 p.m.", ["Stargazing", "Board Games", "Sauna", "Movie", "Library", "Asleep"]),
                                                       ("b", "Shoes", ["Boots", "Slippers", "Sneakers", "Socks"])],
 clues=[
 clue("Awake at Eleven",
  "The portrait was swapped some time between 11 p.m. and midnight on Friday. Dot has confirmed with a peek round every door that guests listed as Asleep at 11 p.m. were indeed sound asleep until morning.",
  "The thief was not Asleep at 11 p.m.", "Guests who were Asleep are cleared", "C", lambda p, X: p["a"] != "Asleep"),
 clue("One Word",
  "The thief’s luggage tag, found tied to the trolley, gave a home city whose name is a single word. Of the sixteen home cities that Frostwood guests come from, the only ones with two-word names are Los Angeles, Quebec City and San Diego.",
  "The thief does not live in Los Angeles, Quebec City or San Diego.", "Guests from Los Angeles, Quebec City and San Diego are cleared", "M",
  lambda p, X: p["home"] not in ("Los Angeles", "Quebec City", "San Diego")),
 clue("The Friday Quiz",
  "Every Doctor, Nurse, Dentist and Teacher in the lodge was in the Great Hall until one in the morning, locked in the final round of the Friday Night Quiz.",
  "The thief is not a Doctor, a Nurse, a Dentist or a Teacher.", "Doctors, Nurses, Dentists and Teachers are cleared", "M",
  lambda p, X: p["occ"] not in ("Doctor", "Nurse", "Dentist", "Teacher")),
 clue("The Roof Terrace",
  "The swap happened at half past eleven. At that moment the Stargazing group was up on the roof terrace with Pippa and the lodge telescope, counting shooting stars, and nobody left before one.",
  "The thief was not Stargazing at 11 p.m.", "Stargazers are cleared", "C", lambda p, X: p["a"] != "Stargazing"),
 clue("Rubber Soles",
  "Dot found a faint print on the polished lobby floor: a ridged rubber sole. Of the shoes in the register, only Boots and Sneakers have ridged rubber soles; Slippers and Socks leave no ridges.",
  "The thief’s Shoes are Boots or Sneakers.", "Slippers and Socks wearers are cleared", "C", lambda p, X: p["b"] in ("Boots", "Sneakers")),
 clue("The Luggage Trolley",
  "The real portrait, in its heavy frame, was wheeled away on the luggage trolley and into the lift. The lift’s log shows it stopped only at the 1st, 3rd and 5th floors that night, and the thief took the trolley to their own floor.",
  "The thief’s room is on the 1st, 3rd or 5th floor.", "Guests on the 2nd and 4th floors are cleared", "M", lambda p, X: p["floor"] in (1, 3, 5)),
 clue("The Steam Room",
  "The sauna closes at half past eleven, and at that moment Gus was at the sauna door handing out towels. Everyone listed in the Sauna at 11 p.m. walked out past him, pink and steaming, and went straight to the Great Hall for cocoa.",
  "The thief was not in the Sauna at 11 p.m.", "Sauna guests are cleared", "C", lambda p, X: p["a"] != "Sauna"),
 clue("The Quiet Wing",
  "The thief chose the lift because it is quiet, and the lift opens straight into the West Wing. The West Wing holds the rooms whose last two digits are 01 to 10 on every floor (for example, 301 to 310).",
  "The thief’s room number ends in 01 to 10.", "East Wing guests (rooms ending 11 to 20) are cleared", "M", lambda p, X: p["num"] <= 10),
 clue("The Winter Garden",
  "Every Beekeeper, Botanist and Florist at Frostwood spent the evening in the Winter Garden at a lecture called <i>What Do Bees Do in the Snow?</i>, which ran until well after midnight.",
  "The thief is not a Beekeeper, a Botanist or a Florist.", "Beekeepers, Botanists and Florists are cleared", "M",
  lambda p, X: p["occ"] not in ("Beekeeper", "Botanist", "Florist")),
 clue("The Readers’ Lock-In",
  "Friday night is the Late Readers’ Lock-In. At eleven o’clock the librarian, Miss Lettice, locked the library door with everybody listed in the Library inside, and unlocked it again at one.",
  "The thief was not in the Library at 11 p.m.", "Library guests are cleared", "C", lambda p, X: p["a"] != "Library"),
 clue("Mountain Light",
  "Painters love the soft morning light on the mountain side of the lodge, and a fresh smear of varnish was found on the windowsill of a mountain-side room. On every floor, the rooms on the mountain side have even numbers.",
  "The thief’s room number is even.", "Odd-numbered rooms are cleared", "M", lambda p, X: p["room"] % 2 == 0),
 clue("If the Movie, then Sneakers",
  "Everyone at the late Movie in the games room had to take their boots off at the door and wear their own shoes. Pippa worked out this rule from the footprints: if the thief was at the Movie, the thief was wearing Sneakers; if the thief was anywhere else, the thief was wearing Boots.",
  "Either the thief was at the Movie and wore Sneakers, or the thief was not at the Movie and wore Boots.",
  "Everyone breaking the Movie/Sneakers/Boots rule is cleared", "C",
  lambda p, X: (p["a"] == "Movie" and p["b"] == "Sneakers") or (p["a"] != "Movie" and p["b"] == "Boots")),
 clue("Paint Fumes",
  "The guest in the room across the hall from the thief’s complained to Dot about “a smell of paint” coming from over the way. Across the hall means the facing room: every odd-numbered room faces the next even number (Room 105 faces 106; Room 519 faces 520). Every guest in the lodge is on this register.",
  "The room directly across the hall from the thief’s room is occupied (at least one guest on the register is staying in it).",
  "Guests whose facing room is empty are cleared", "M", lambda p, X: len(X.across(p)) > 0),
 clue("The Signature",
  "The copy of the portrait was signed in the corner, very small, with the copier’s own initials. The first initial comes later in the alphabet than the second: the first letter of the thief’s first name comes after the first letter of their surname.",
  "The first letter of the thief’s first name comes later in the alphabet than the first letter of the thief’s surname.",
  "Guests whose first initial comes before or equals their surname initial are cleared", "M",
  lambda p, X: p["first"][0] > p["last"][0]),
 ]))
